module "console"

suggestions =
{
	["exit_game"] = "退出游戏",
	["exit"] = "退出游戏",
	
	-- Debug commands 
	
	["camera_mode"] = "切换为摄像机控制模式",
	["show_bound_box"] = "显示模型包围盒",
	["show_move_map"] = "显示寻径图",
	--["rtdebug"] = "",
	--["local_speed"] = "",\
	--["goto"] = "",
	--["c2scmd"] = "向GS发送调试命令",
	--["d"] = "向GS发送调试命令",
	["c2dcmd_ints"] = {args = "<cmd id> <参数2> <参数3>...", text = "向DS发送调试命令(整型参数)"},
	["view_radius"] = "",
	["relogin"] = "退出并重新登录当前线",
	["skill"] = {args = "<id>", text = "释放技能"},
	["render_water"] = "",
	["render_grass"] = "",
	["render_forest"] = "",
	["render_shadow"] = "",
	["testdist"] = "",
	["gfx"] = "播放gfx",
	["clear_gfx_cache"] = "清除gfx缓存",
	["show_pos"] = "在模型头上显示系统坐标",
	["show_action"] = "在模型头上显示当前动作",
	["show_id"] = "开启玩家xid、物品id、技能id、任务id、军团id的显示",
	["a3dstat"] = "",
	["musicinfo"] = "音乐数据",
	["game_static"] = "游戏统计数据",
	["log_textures"] = "将游戏中贴图信息输出到日志中",
	["log_process_info"] = "输出游戏内存占用等信息",
	["log_memory_info"] = "记录内存",
	["log_npc_list"] = "输出当前的NPC列表",
	["log_terrain_textures"] = "输出地表贴图信息",
	["ui_info"] = "界面数据",
	["ui_gc"] = {args = "[idle_threshold] [gc_interval]", text = "设置界面自动销毁参数。idle_threshold: 界面空闲时间，gc_interval: 每隔多久进行一次销毁操作"},
	["default_settings"] = "默认所有系统设置",
	["treelod"] = "",
	["fps"] = "显示FPS",
	["player_radius"] = "",
	["skip_frame"] = "",
	["model_update"] = "",
	["mini_dump"] = "",
	["memory_dump"] = "",
	["memory_enable"] = "",
	["memory_disable"] = "",
	["memory_addi"] = "",
	["set_time_of_day"] = {args = "<小时> <分钟>", text = "设置当前场景的时间"},
	["get_server_time"] = "获得服务器时间",
	["get_pvp_debug_time"] = "获得pvp调试时间",
	["d_task"] = "",
	["mipmapbias"] = "",
	["trncull"] = "",
	--["gscmd"] = "",
	--["c2dcmd"] = "",
	--["protocol"] = "",
	["cam_param"] = "",
	["reset_help"] = "重置新手帮助信息",
	["reset_sequence"] = "重置连招信息",
	["exploit"] = "",
	["skin_light"] = "",
	["model_light_map"] = {args = "<on|off>", text = "关闭/打开光影贴图"},
	["terrain_hdr"] = "切换地形HDR开关",
	["d_uiinfo"] = "显示UI相关调试信息",
	["show_strong"] = "显示NPC强壮系数",
	["net_delay"] = {args = "<delayValue>", text = "设置客户端模拟网络延迟（毫秒）"},
	["lua"] = {args = "[lua_code]", text = "执行lua脚本，如果后面不跟lua代码，进入lua交互模式（可输入end_lua退出）"},
	["lua_debug"] = "开始使用LDT进行lua debug，请先在LDT中开启调试服务器后再运行此命令",
	["cosmos_debug"] = {args = "操作编号", text = "小宇宙操作, 0:激活, 1:开孔, 2:装石头, -2:卸石头"},
	["cosmos_value"] = {args = "[增加潜能值=1000]", text = "小宇宙增加n点潜能值"},
	["cosmos_clear"] = "清空小宇宙",
	["cosmos_info"] = "显示当前小宇宙和星魂链状态",	
	["hide_back_show_target"] = "临时测试使用,小宇宙爆发状态下是否显示目标",
	["listen"] = {args = "<dlv | gs | 2dlv | 2gs> <off | on_exclude>", text = "显示deliver和gs的消息"},
	["reload_lua_files"] = "重新加载ConfigList.lua中配置的所有脚本(配置脚本)",
	["reload_audio"] = "重新加载Audio",
	["rebuild_shaders"] = "重新编译所有shader",
	["play_animation"] = {args = "<动画id>", text = "播放动画测试短片"},
	["play_camera"] = {args = "<摄像机id>", text = "播放测试摄像机"},
	["play_swf"] = {args = "<swf文件路径>", text = "播放swf动画"},
	["play_system_ani"] = {args = "<系统id>", text = "播放开启某个系统的动画"},
	["clear_bag"] = "关闭安全锁，并销毁玩家背包中所有可以销毁的物品（慎用）",
	["show_dialog"] = {args = "<dlg_name> ", text = "强制显示UI界面"},
	["show_buff"] = "显示玩家身上的buff id列表",
	["double_exp"] = {args = "<on|off|增加的双倍经验时间>", text = "开启/关闭双倍经验模式，或增加双倍经验时间"},
	["stored_exp_add"] = {args = "<value>", text = "增加储存经验"},
	["stored_exp_trans"] = {args = "<value>", text = "转化储存经验"},
	["themes"] = {args = "<Default | Themes1 | Themes2> ", text = "切换界面主题, 参数为空则循环切换"},
	["verbose"] = {args = "<on|off>", text = "是否在错误信息中显示详细信息（例如错误ID等）"},
	["skip_client_validation"] = {args = "<on|off>", text = "是否跳过UI中某些功能的客户端检测（用于测试服务器逻辑）"},
	["broadcast"] = {args = "<msg>", text = "发送广播消息"},
	["show_perf"] = "测试游戏各模块运行效率开关",
	["cross_info"] = "调试跨服",
	["multi_render"] = {args = "开/关", text = "多线程渲染开关, 0:关, 1:开"},
	["gfx_enable"] = {args = "开/关", text = "光效开关, 0:关, 1:开"},
	["show_brush"] = {args = "开/关", text = "凸包显示开关, 0:关, 1:开"},
	["path_move"] = {args = "<模板id>", text = "测试强制移动"},
	["switch_prof"] = {args = "<职业id>", text = "切换职业。2天马,3白鸟,4天龙,5仙女,6凤凰,7双子" },
	["set_server_time"] = {args = "<年> <月> <日> <时> <分>", text = "设置服务器时间，服务器重启后恢复正常时间。据说只能在15线使用。"},
	["uiloadall"] = "加载所有未加载界面",
	["help_notify"] = {args = "<type><id>", text = "指引测试命令"},
	["trig_captcha"] = "触发反外挂答题",
	["award_captcha"] = "直接获得反外挂答题奖励",
	["add_friendship"] = {args = "<value>", text = "增加友好度"},	
	["role_info"] = "显示调试用的角色属性信息",	
	["photo_book_add"] = {args = "<id>", text = "开启图鉴"},
	["assist_distant"] = {args = "距离", text = "设置Tab选怪距离"},

	["dungeon_create"] = {args = "<tid>", text = "开启副本"},
	["dungeon_close"] = "关闭玩家当前在的副本（玩家会被踢出，所有人）",
	["dungeon_exit"] = "玩家从副本里返回到进副本前的线跟地图",
	["dungeon_create_f"] = {args = "<tid>", text = "强制开启副本(自由模式，队伍里有人不满足条件，但自己得满足）"},
	["dungeon_enter"] = {args = "<tid>", text = "进入副本, 当组队有副本开启时，可以在任意大地图线进。"},
	["dungeon_counter_clear"] = "清除副本进入次数计数",
	
	["grass_press"]	= {args = "<半径> <偏移大小>", text = "草被压倒的属性"},
	["grass_shake"]	= {args = "<速度> <阻尼> ", text = "草摇晃的属性"},
	["occlusion_culling"] = "是否使用新的剪裁",
	["RenderScene"] = "",
	["RenderSky"] = "",
	["RenderTerrain"] = "",
	["RenderSceneObject"] = "",
	["AnimationWorld"] = "",
	["RenderLitModel"] = "",
	["RenderSkinModel"] = "",
	["RenderGrass"] = "",
	["RenderShadow"] = "",
	["RenderWater"] = "",
	["RenderGFX"] = "",
	["RenderPostProcess"] = "",
	["RenderUI"] = "",	
		
	-- C2S Commands	
	["get_item"] = {args = "<物品id> [数量=1] [过期时间(秒)=0]", text = "获得指定物品1个或多个，数量不填为1，时间不填则不过期"},
	["get_cloth"] = {args = "<物品id>", text = "获得指定圣衣"},
	["move_tempitem"] = {args = "[临时包裹位置=0] [数量=1] [包裹位置=0]", text = "移动临时包裹物品到背包中,位置起始位置为0"},
	["get_tempitem"] = {args = "<物品id> [数量=1] [过期时间(秒)=0]", text = "临时包裹获得指定物品1个或多个，数量不填为1，时间不填则不过期"},
	["get_item_sequence"] = {args = "<物品id1> <物品id2>", text = "依次获得从id1到id2的物品"},
	["gen_monster"] = {args = "<怪物id> [数量=1] [存在时间=100]", text = "抛怪物，数量默认为1，存在时间默认100"},
	["teleport"] = {args = "<场景id> <坐标x> <坐标z>", text = "传送到指定场景的指定坐标"},
	["teleport_test"] = "测试不断传送场景",
	["full_hp_mp"] = "信春哥,满血满魔",
	["level_up"] = {args = "[level]", text = "升级（不填参数升1级，填参数level直接升到level级）"},
	["money"] = "金币",
	["bind_money"] = "绑定币",
	["rmb"] = "元宝",
	["set_y"] = {args = "<坐标y>", text = "飞高(即设置y轴坐标值)"},
	["set_vp"] = {args = "<斗气值>", text = "设置玩家斗气值"},
	["speed"] = {args = "[人物速度=20]", text = "将内服人物速度调至n米/秒（20是上限）"},
	
	["learn_skill"] = {args = "<id> [等级]", text = "学习技能，不填等级则默认学习下一级"},
	["forget_skill"] = {args = "<id>", text = "遗忘技能"},
	["produce_skill_exp"] = {args = "<id> <经验值>", text = "对应生产技能获得经验值"},
	["produce_skill_level_up"] = {args = "<id>", text = "对应的生产技能升级"},
	
	["pet_level"] = {args = "<宠物索引> <等级>", text = "宠物直接升级到指定的等级"},
	
	["reload_ai_script"] = "重载AI脚本",
	["gen_ore"] = {args = "<id>", text = "生成矿物"},
	
	["add_title"] = {args = "<title_id>", text = "加称号"},
	["remove_title"] = {args = "<title_id>", text = "去除称号"},
	
	["set_home"] = {args = "[<世界号> <x坐标> <z坐标>]", text = "设置玩家回城点（所有参数不填则设当前坐标为回城点）"},
	
	["safe_lock_off"] = "取消玩家时间锁",
	
	["add_repu"] = {args = "<id> <value>", text = "增加玩家声望值，可为负数，即减少声望"},
	["set_repu"] = {args = "<id> <value>", text = "设置玩家声望值"},
	["show_repu"] = {args = "[id1] [id2] [id3] ...", text = "显示玩家声望值，可填多个id，不填id则显示所有声望(0~31)"},

	["show_team_repu"] = {args = "[id1] [id2] [id3] ...", text = "显示玩家队伍/团队声望值，可填多个id，不填id则显示所有声望(0~4)"},

	["show_league_repu"] = {args = "[id1] [id2] [id3] ...", text = "显示玩家军团声望值，可填多个id，不填id则显示所有声望(0~31)"},
	["show_league_inc_repu"] = {args = "<id>", text = "显示玩家军团增量声望，只能填写一个id"},
	["show_league_inc_repu day"] = {args = "<id>", text = "显示玩家军团部分增量声望-日，只能填写一个id"},
	["show_league_inc_repu week"] = {args = "<id>", text = "显示玩家军团部分增量声望-周，只能填写一个id"},
	["show_league_inc_repu month"] = {args = "<id>", text = "显示玩家军团部分增量声望-月，只能填写一个id"},

	["add_account_repu"] = {args = "<id> <value>", text = "增加帐号声望值，可为负数，即减少声望"},
	["set_account_repu"] = {args = "<id> <value>", text = "设置帐号声望值"},
	
	["add_inc_repu"] = {args = "<id> <cur | last>-<day | week | month> <value>", text = "增加或者减少id对应的个人增量声望，value可正可负"},
	["add_inc_repu day"] = {args = "<id> <cur | last> <value>", text = "增加或者减少id对应的个人部分增量声望-日，value可正可负"},
	["add_inc_repu week"] = {args = "<id> <cur | last> <value>", text = "增加或者减少id对应的个人部分增量声望-周，value可正可负"},
	["add_inc_repu month"] = {args = "<id> <cur | last> <value>", text = "增加或者减少id对应的个人部分增量声望-月，value可正可负"},

	["controller"] = {args = "<on|off> <id>", text = "开关控制器"},
	["test_text_pack"] = {args = "<文本包id> <次数>", text = "测试文本包"},
	["test_monster_pack"] = {args = "<怪物包id> <次数>", text = "测试怪物包"},
	
	["show_global_params"] = {args = "[id1] [id2]", text = "显示id1到id2之间的全局参数，只填id1则显示id1对应参数，都不填则显示全部参数"},
	["add_global_params"] = {args = "<id> [value=1]", text = "使id对应的全局参数增加value，value不填默认为1"},
	["show_scene_params"] = {args = "[id1] [id2]", text = "显示id1到id2之间的场景参数，只填id1则显示id1对应参数，都不填则显示全部参数"},
	["add_scene_params"] = {args = "<id> [value=1]", text = "使id对应的场景参数增加value，value不填默认为1"},
	["show_combat_power"] = "显示玩家战斗力",
	["show_constellation_data"] = {args = "[id1] [id2] [id3] ...", text = "显示当前场景星座运势参数，可填多个id，不填id则显示所有参数(0~11)"},

	["league_level"] = {args = "<level>", text = "设置军团等级"},
	["league_del"] = "彻底删除当前玩家所在军团（慎用）",
	["league_add_repu"] = {args = "<id> <value>", text = "增加或者减少id对应的军团声望，value可正可负，id取值范围0到31"},
	["league_add_inc_repu"] = {args = "<id> <cur | last>-<day | week | month> <value>", text = "增加或者减少id对应的军团增量声望，value可正可负"},
	["league_add_inc_repu day"] = {args = "<id> <cur | last> <value>", text = "增加或者减少id对应的军团部分增量声望-日，value可正可负"},
	["league_add_inc_repu week"] = {args = "<id> <cur | last> <value>", text = "增加或者减少id对应的军团部分增量声望-周，value可正可负"},
	["league_add_inc_repu month"] = {args = "<id> <cur | last> <value>", text = "增加或者减少id对应的军团部分增量声望-月，value可正可负"},
	["league_base_recycle"] = "收回玩家所属的军团基地",

	--调试命令
	["d_c2scmd 2001"] = {args = "<经验>",text = "加经验，支持正负"},
	["c2dcmd 402"] = {args = "<小时>-<分钟>", text = "设置deliver pvp 调试时间"},
	["c2scmd 2070"] = "清除VIP领奖记录",		
	["c2dcmd 305"] = {args = "<充几分钱> <充值时间改到几天前> <本月充值改为几星币> <上月充值改为几星币>", text = "修改VIP充值数据"},	
	["d 2043"] = {args = "<技能id> <技能等级>", text = "学习斗魂技能"},
	["d_c2scmd 6014"] = {args = "<等级>",text = "直接升级"},
	["d 5030"] = "清空探索区域",
	["d 5031"] = "清空链",
	["d 5032"] = {args = "<微粒id> <微粒个数>",text = "获得微粒 id 0-9,个数可以为负"},
	["d_c2scmd 5040"] = {args = "<灵力>", text = "直接设置主角的灵力值"},
	-- Task Commands

	["task list \\t"] = "显示用户已接任务状态",
	["task list \\t templ"] = {args = "[taskid]", text = "显示客户端任务模板内容"},
	["task trig"]    = {args = "<taskid>", text = "手动触发taskid对应任务"},
	["task trig_f"]  = {args = "<taskid>", text = "强制触发taskid对应任务"},
	["task award"]   = {args = "<taskid>", text = "强制完成taskid对应任务并发成功奖励"},
	["task giveup"]  = {args = "<taskid>", text = "手动放弃taskid对应任务"},
	["task rmfin"]  = {args = "<taskid>", text = "强制移除任务已完成标志"},
	--["task d_storage_refresh"] = {args = "[库id]", text = "无id时，强制开始一个新的库刷新周期; 有id时，正常手动刷新库，消耗对应开销"},
	["task chat_test"] = "程序用:测试聊天频道显示位置",
	["task show_npc"] = "强制显示因任务隐藏的NPC",
	["task_disable"] = {args = "<taskid>", text = "禁用任务"},
	["task_enable"] = {args = "<taskid>", text = "解禁任务"},
	
	-- Tools

	["shortcut"] = {args = "<其他控制台命令，以;分割多条命令>", text = "为控制台命令创建快捷方式，可拖动到快捷栏执行"},
	["batch"] = {args = "<其他控制台命令，以;分割多条命令>", text = "一次执行多个命令，以分号分隔"},
	["loop"] = {args = "<N> <其他控制台命令，以;分割多条命令>", text = "重复执行N次多个命令，以分号分隔"},

	-- Arena
	["arena_dump"] = "打印个人竞技场信息",
	["arena_set_tm_virtual"] = {args = "<年> <月> <日> <时> <分> <秒>", text = "设置虚拟时间，将系统虚拟时间设置为指定值"},	
	["arena_set_tm_pairing_interval"] = {args = "<秒>", text = "设置配对时间间隔"},
	["arena_set_tm_pairing_countdown"] = {args = "<秒>", text = "设置配对后邀请玩家进入倒计时"},
	["arena_set_pairing_threshold_score"] = {args = "<积分阈值>", text = "设置匹配积分阈值"},
	["arena_set_max_weekly_join_count"] = {args = "<天>", text = "设置周参加次数上限"},	

	-- 灵魂之甲
	["add_soul_armor"] = {args = "<铠甲id> <铠甲等级>", text = "激活某个部位的灵魂之甲"},	

	-- 通告
	["world_broadcast_item"] = {args = "<itemid> <lotteryid> <广播次数>", text = "测试自己获奖状况"},

	["dump_npc"] = "将所有npc的id和模板id写如ec.log",

	["set_load"] = {args = "<加载编号> <标记>", text = "标记0不加载、1加载;编号1:装饰物,2:TerrainData,3:地形轮廓,4:玩家,5:Npc,6:ui"},
	["test_map"] = "跳跃指定点，记录内存",	
}
