local GameApi = GameApi

---所有动作类型
MINIPET_ACTION_STAND			= 0
MINIPET_ACTION_BORN				= 1
MINIPET_ACTION_DISAPPEAR	= 2
MINIPET_ACTION_WALK				= 3
MINIPET_ACTION_RUN 				= 4
MINIPET_ACTION_TRAIN_1		= 5
MINIPET_ACTION_TRAIN_2		= 6
MINIPET_ACTION_TRAIN_3		= 7
MINIPET_ACTION_TRAIN_4		= 8
MINIPET_ACTION_TRAIN_5		= 9
MINIPET_ACTION_TRAIN_6		= 10
MINIPET_ACTION_TRAIN_7		= 11

---所有种类
MINIPET_RACE_CAT 					= 0
MINIPET_RACE_DOG					=	1
MINIPET_RACE_PARROT				= 2
MINIPET_RACE_EAGLE				= 3
MINIPET_RACE_PENGUIN			= 4


---种类默认动作
DEFAULT_MINIPET_ACTION = {}
DEFAULT_MINIPET_ACTION[MINIPET_ACTION_STAND] 			= "站立"
DEFAULT_MINIPET_ACTION[MINIPET_ACTION_BORN] 			= "出现"
DEFAULT_MINIPET_ACTION[MINIPET_ACTION_DISAPPEAR] 	= "消失"
DEFAULT_MINIPET_ACTION[MINIPET_ACTION_WALK] 			= "行走"
DEFAULT_MINIPET_ACTION[MINIPET_ACTION_RUN] 				= "奔跑"
DEFAULT_MINIPET_ACTION[MINIPET_ACTION_TRAIN_1] 		= "蹲坐"
DEFAULT_MINIPET_ACTION[MINIPET_ACTION_TRAIN_2] 		= "伸懒腰"
DEFAULT_MINIPET_ACTION[MINIPET_ACTION_TRAIN_3] 		= "跳跃"
DEFAULT_MINIPET_ACTION[MINIPET_ACTION_TRAIN_4] 		= "打滚儿"
DEFAULT_MINIPET_ACTION[MINIPET_ACTION_TRAIN_5] 		= "持续卧坐"
DEFAULT_MINIPET_ACTION[MINIPET_ACTION_TRAIN_6] 		= "持续趴下"
DEFAULT_MINIPET_ACTION[MINIPET_ACTION_TRAIN_7] 		= "持续蹲坐"


MINIPET_ACTION = {}
MINIPET_ACTION[MINIPET_RACE_CAT] 			= DEFAULT_MINIPET_ACTION
MINIPET_ACTION[MINIPET_RACE_DOG] 			= DEFAULT_MINIPET_ACTION
MINIPET_ACTION[MINIPET_RACE_PARROT] 	= DEFAULT_MINIPET_ACTION
MINIPET_ACTION[MINIPET_RACE_EAGLE] 		= DEFAULT_MINIPET_ACTION
MINIPET_ACTION[MINIPET_RACE_PENGUIN] 	= DEFAULT_MINIPET_ACTION
		
--- race: 0-猫, 1-狗, 2-鹦鹉, 3-老鹰, 4-企鹅
MiniPet_Action = {}
function MiniPet_Action:GetECMName (action , race)
	local action_name = ""
	if MINIPET_ACTION[race]~=nil then
		if MINIPET_ACTION[race][action]~=nil then
			action_name = MINIPET_ACTION[race][action]
		end
	end
	return action_name
end