//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AnimationEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_OBJECT_LIST                 101
#define IDD_BEZIER_LIST                 102
#define IDD_DLG_WORLD                   103
#define IDR_HTML_ACTIONQTEGLG           104
#define IDR_MAINFRAME                   128
#define IDR_MAIN_TOOLBAR                128
#define IDR_ANIMATTYPE                  129
#define IDD_DLG_NEW_OBJECT              135
#define IDD_TRACK_PANEL                 136
#define IDD_DLG_GROUP                   137
#define IDD_DLG_CHANNEL                 138
#define IDD_DLG_NEW_ACTION              139
#define IDD_DLG_ACTION_MOVE             141
#define IDD_DLG_SET_TIME                142
#define IDD_DLG_ACTION_BEZIER_MOVE      143
#define IDD_DLG_ACTION_BEZIER_POINT     144
#define IDD_DLG_ACTION_JUMP             145
#define IDD_DLG_ACTION_MOTION           146
#define IDD_DLG_ACTION_DISPLAY_HIDE     147
#define IDD_DLG_ACTION_DIALOGUE         148
#define IDD_DLG_PLAYER                  149
#define IDD_DLG_OBJECT                  150
#define IDD_DLG_BEZIER                  151
#define IDD_DLG_ACTION_SOUND            152
#define IDD_DLG_ACTION_HOOK             153
#define IDD_DLG_ACTION_SPEED_CONTROL    154
#define IDD_DLG_ACTION_SCALE            155
#define IDD_DLG_ACTION_CAMERA_FILTER    156
#define IDD_DLG_ACTION_CAMERA_OSCILLATORY 157
#define IDD_DLG_BIND_CAMERA             158
#define IDD_DLG_MOVE_ACTIONS            159
#define IDD_DLG_ACTION_TRANSPARENT      160
#define IDD_DLG_ACTION_HIDE_WORLD       161
#define IDD_DLG_ACTION_FOV              162
#define IDD_DLG_ACTION_ROTATE           163
#define IDD_DLG_ACTION_DOF              164
#define IDD_DLG_ACTION_BLOOM            165
#define IDD_DLG_ACTION_RADIAL_BLUR      166
#define IDD_DLG_ACTION_MOTION_BLUR      167
#define IDD_DLG_ACTION_WARP             168
#define IDD_DLG_ACTION_CC               169
#define IDD_DLG_ACTION_ADD_SKIN         170
#define IDD_DLG_ACTION_GOD_RAY          171
#define IDD_DLG_ACTION_QTE              172
#define IDD_DLG_SET_WORLD_OFFSET        173
#define IDB_BITMAP_SYS                  190
#define IDC_OBJECT_LIST                 1013
#define IDC_BUTTON_NEW_OBJECT           1014
#define IDC_BUTTON_REMOVE_OBJECT        1015
#define IDC_BEZIER_LIST                 1016
#define IDC_BUTTON_COPY_OBJECT          1016
#define IDC_BUTTON_CAMERA               1017
#define IDC_BUTTON_WORLD                1018
#define IDC_BUTTON_PLAYER               1019
#define IDC_BUTTON_NEW_BEZIER           1020
#define IDC_BUTTON_WORLD_OK             1021
#define IDC_BUTTON_REMOVE_BEZIER        1021
#define IDC_BUTTON_WORLD_CANCEL         1022
#define IDC_BUTTON_DISPLAY_BEZIER       1022
#define IDC_BUTTON_WORLD_IMPORT         1023
#define IDC_BUTTON_HIDE_BEZIER          1023
#define IDC_WORLD_FILE_NAME             1025
#define IDC_WORLD_INSTANCE              1025
#define IDC_NEW_OBJECT_FILE_NAME        1026
#define IDC_BUTTON_NEW_OBJECT_IMPORT    1027
#define IDC_BUTTON_NEW_OBJECT_OK        1028
#define IDC_BUTTON_NEW_OBJECT_CANCEL    1029
#define IDC_HSCROLLBAR                  1033
#define IDC_VSCROLLBAR                  1034
#define IDC_BUTTON_NEW_GROUP            1034
#define IDC_GROUP_ID                    1035
#define IDC_BUTTON_SET_TIME             1035
#define IDC_BUTTON_SET_FRAMES           1035
#define IDC_GROUP_NAME                  1036
#define IDC_BUTTON_NEW_CHANNEL          1036
#define IDC_BUTTON_GROUP_OK             1037
#define IDC_BUTTON_GROUP_CREATE_CHANNEL 1038
#define IDC_BUTTON_GROUP_REMOVE         1039
#define IDC_BUTTON_GROUP_CANCEL         1040
#define IDC_CHANNEL_NAME                1042
#define IDC_BUTTON_CHANNEL_REMOVE       1043
#define IDC_BUTTON_CHANNEL_OK           1044
#define IDC_BUTTON_CHANNEL_CANCEL       1045
#define IDC_CHANNEL_OBJECT              1046
#define IDC_CHANNEL_ID                  1047
#define IDC_ACTION_TYPE                 1048
#define IDC_START_TIME                  1049
#define IDC_BUTTON_NEW_ACTION_OK        1050
#define IDC_MOVETO_FRAME                1050
#define IDC_BUTTON_NEW_ACTION_CANCEL    1051
#define IDC_ACTION_ID                   1052
#define IDC_OBJECT_ID                   1053
#define IDC_OBJECT_TYPE                 1054
#define IDC_START_POS_X                 1055
#define IDC_START_POS_Y                 1056
#define IDC_START_POS_Z                 1057
#define IDC_END_POS_X                   1058
#define IDC_ORI_X                       1058
#define IDC_END_POS_Y                   1059
#define IDC_ORI_Y                       1059
#define IDC_END_POS_Z                   1060
#define IDC_ORI_Z                       1060
#define IDC_CLOSE_TERRAIN               1061
#define IDC_ORI_W                       1061
#define IDC_START_VELOCITY              1062
#define IDC_ACCELERATION_PERCENT        1062
#define IDC_USE_ORIENTATION             1062
#define IDC_END_VELOCITY                1063
#define IDC_TOTAL_FRAMES                1063
#define IDC_BUTTON_ACTION_MOVE_OK       1064
#define IDC_START_FRAME                 1064
#define IDC_VOLUME                      1064
#define IDC_TRANSPARENT                 1064
#define IDC_MOVE_ORI_X                  1064
#define IDC_BUTTON_ACTION_MOVE_CANCEL   1065
#define IDC_START_SECONDS               1065
#define IDC_BLEND_FRAMES                1065
#define IDC_MOVE_ORI_Y                  1065
#define IDC_ACTION_NAME                 1066
#define IDC_MOVE_ORI_Z                  1066
#define IDC_SET_TIME                    1067
#define IDC_MOTION_TYPE                 1067
#define IDC_MOVE_ORI_W                  1067
#define IDC_BUTTON_SET_TIME_OK          1068
#define IDC_MOTION_SPEED                1068
#define IDC_ROTATE_END_X                1068
#define IDC_BUTTON_SET_TIME_CANCEL      1069
#define IDC_ROTATE_END_Y                1069
#define IDC_BUTTON_SET_START_POS        1070
#define IDC_ROTATE_END_Z                1070
#define IDC_BUTTON_SET_END_POS          1071
#define IDC_ROTATE_END_W                1071
#define IDC_BUTTON_ACTION_MOVE_REMOVE   1072
#define IDC_BUTTON_SET_ORIENTATION      1072
#define IDC_BUTTON_SET_START_ANGLE      1073
#define IDC_BUTTON_SET_END_ROTATE       1073
#define IDC_BEZIER_ID                   1074
#define IDC_BUTTON_SET_END_ANGLE        1074
#define IDC_BUTTON_ACTION_BEZIER_MOVE_REMOVE 1075
#define IDC_BUTTON_SET_START_ANGLE_AS_MOVE 1075
#define IDC_BUTTON_ACTION_BEZIER_MOVE_OK 1076
#define IDC_BUTTON_SET_END_ANGLE_AS_MOVE 1076
#define IDC_BUTTON_ACTION_BEZIER_MOVE_CANCEL 1077
#define IDC_BUTTON_ACTION_BEZIER_POINT_OK 1079
#define IDC_BUTTON_ACTION_BEZIER_POINT_CANCEL 1080
#define IDC_BEZIER_POINT_ID             1081
#define IDC_BEZIER_FOV                  1082
#define IDC_BUTTON_ACTION_JUMP_REMOVE   1082
#define IDC_BUTTON_ACTION_JUMP_CANCEL   1083
#define IDC_BUTTON_ACTION_JUMP_OK       1084
#define IDC_BUTTON_ACTION_MOTION_REMOVE 1085
#define IDC_BUTTON_ACTION_MOTION_OK     1086
#define IDC_BUTTON_ACTION_MOTION_CANCEL 1087
#define IDC_VISABLE_TYPE                1088
#define IDC_BUTTON_ACTION_DISPLAY_HIDE_REMOVE 1089
#define IDC_BUTTON_ACTION_DISPLAY_HIDE_OK 1090
#define IDC_BUTTON_ACTION_DISPLAY_HIDE_CANCEL 1091
#define IDC_NEW_OBJECT_TYPE             1092
#define IDC_BUTTON_ACTION_DIALOGUE_OK   1093
#define IDC_BUTTON_ACTION_DIALOGUE_CANCEL 1094
#define IDC_BUTTON_ACTION_DIALOGUE_REMOVE 1095
#define IDC_DIALOGUE                    1096
#define IDC_PLAYER_FILE_NAME            1101
#define IDC_BUTTON_PLAYER_IMPORT        1102
#define IDC_BUTTON_PLAYER_OK            1103
#define IDC_BUTTON_PLAYER_CANCEL        1104
#define IDC_OBJECT_NAME                 1105
#define IDC_OBJECT_FILE_NAME            1106
#define IDC_BUTTON_OBJECT_IMPORT        1107
#define IDC_BUTTON_OBJECT_OK            1108
#define IDC_BUTTON_OBJECT_CANCEL        1109
#define IDC_BEZIER_NAME                 1110
#define IDC_BUTTON_BEZIER_OK            1111
#define IDC_BUTTON_BEZIER_CANCEL        1112
#define IDC_BUTTON_ACTION_SOUND_REMOVE  1113
#define IDC_BUTTON_ACTION_SOUND_OK      1114
#define IDC_BUTTON_ACTION_SOUND_CANCEL  1115
#define IDC_BUTTON_SOUND_IMPORT         1116
#define IDC_SOUND_FILE_NAME             1117
#define IDC_BUTTON_TEX2_IMPORT          1118
#define IDC_SOUND_EVENT_NAME            1118
#define IDC_HOOK_NAME                   1119
#define IDC_TEX2_FILE_NAME              1119
#define IDC_HANGER_NAME                 1120
#define IDC_FILTER_TYPE                 1120
#define IDC_HOOK_OBJECT_ID              1121
#define IDC_ELSE_HOOK_NAME              1122
#define IDC_BUTTON_ACTION_HOOK_OK       1123
#define IDC_BUTTON_ACTION_HOOK_CANCEL   1124
#define IDC_BUTTON_ACTION_HOOK_REMOVE   1125
#define IDC_BUTTON_COPY_BEZIER          1126
#define IDC_BEZIER_NODE_LIST            1127
#define IDC_START_ANGLE                 1128
#define IDC_BUTTON_COPY_BEZIER_POINT_INFO 1128
#define IDC_END_ANGLE                   1129
#define IDC_SPEED                       1129
#define IDC_BUTTON_PASTE_BEZIER_POINT_INFO 1129
#define IDC_BUTTON_ACTION_SPEED_OK      1130
#define IDC_BUTTON_INSERT_BEZIER_POINT  1130
#define IDC_ROTATE_ANGLE                1130
#define IDC_BUTTON_ACTION_SPEED_CANCEL  1131
#define IDC_DISPLACEMENT                1131
#define IDC_BUTTON_REMOVE_BEZIER_POINT  1131
#define IDC_BUTTON_ACTION_SPEED_REMOVE  1132
#define IDC_FREQUENCY                   1132
#define IDC_START_SCALE                 1133
#define IDC_END_SCALE                   1134
#define IDC_POS_X                       1138
#define IDC_POS_Y                       1139
#define IDC_START_NEAR_FOCUS            1139
#define IDC_POS_Z                       1140
#define IDC_END_NEAR_FOCUS              1140
#define IDC_START_FAR_FOCUS             1141
#define IDC_BUTTON_ACTION_OK            1142
#define IDC_BUTTON_ACTION_CANCEL        1143
#define IDC_BUTTON_ACTION_REMOVE        1144
#define IDC_END_FAR_FOCUS               1145
#define IDC_BUTTON_CHOOSE_COLOR         1146
#define IDC_START_FAR_BLUR              1146
#define IDC_OSCILLATORY_TYPE            1147
#define IDC_END_FAR_BLUR                1147
#define IDC_START_CLAMP_BLUR            1148
#define IDC_END_CLAMP_BLUR              1149
#define IDC_SPECIFY_TIME                1150
#define IDC_START_OUT_FOCUS_DISTANCE    1150
#define IDC_RAIN                        1151
#define IDC_END_OUT_FOCUS_DISTANCE      1151
#define IDC_SNOW                        1152
#define IDC_SPECIFY_WEATHER             1153
#define IDC_WORLD_TIME_HOUR             1154
#define IDC_WORLD_TIME_MINUTE           1155
#define IDC_USE_HOST_PLAYER             1155
#define IDC_WORLD_TIME_SECOND           1156
#define IDC_FORCE_NO_SAINT_CLOTH        1156
#define IDC_SHOW_GFX                    1157
#define IDC_BEZIER_VISABLE              1158
#define IDC_BUTTON_BIND_CAMERA_OK       1159
#define IDC_BUTTON_BIND_CAMERA_CANCEL   1160
#define IDC_OFFSET_X                    1161
#define IDC_OFFSET_Y                    1162
#define IDC_OFFSET_Z                    1163
#define IDC_BUTTON_MOVE_ACTIONS_OK      1164
#define IDC_BUTTON_MOVE_ACTIONS_CANCEL  1165
#define IDC_END_TIME                    1168
#define IDC_ROTATE_AXIS_TYPE            1172
#define IDC_OSCILLATORY_ATTENUATION     1173
#define IDC_MOVE_ACTIONS_LOG            1174
#define IDC_OSCILLATORY_AXIS            1175
#define IDC_START_TRANSPARENT           1176
#define IDC_END_TRANSPARENT             1177
#define IDC_HIDE_WORLD_TYPE             1178
#define IDC_BUTTON_CHOOSE_BACKGROUND_COLOR 1179
#define IDC_MOVE_OPERATION              1180
#define IDC_START_FOV                   1181
#define IDC_END_FOV                     1182
#define IDC_ROTATE_START_W              1183
#define IDC_ROTATE_START_X              1184
#define IDC_ROTATE_START_Y              1185
#define IDC_ROTATE_START_Z              1186
#define IDC_BUTTON_SET_START_ROTATE     1187
#define IDC_START_NEAR_BLUR             1188
#define IDC_ROTATE_A_X                  1188
#define IDC_END_NEAR_BLUR               1189
#define IDC_ROTATE_A_Y                  1189
#define IDC_START_BLUR_SIZE             1190
#define IDC_ROTATE_A_Z                  1190
#define IDC_END_BLUR_SIZE               1191
#define IDC_ROTATE_A_W                  1191
#define IDC_START_BRIGHT_THRESHOLD      1192
#define IDC_BUTTON_SET_A                1192
#define IDC_END_BRIGHT_THRESHOLD        1193
#define IDC_ROTATE_B_X                  1193
#define IDC_START_BRIGHT_SCALE          1194
#define IDC_ROTATE_B_Y                  1194
#define IDC_END_BRIGHT_SCALE            1195
#define IDC_ROTATE_B_Z                  1195
#define IDC_START_BLUR_BLUR_MAX         1196
#define IDC_ROTATE_B_W                  1196
#define IDC_START_BLEND_THRESHOLD       1196
#define IDC_END_BLUR_BLUR_MAX           1197
#define IDC_BUTTON_SET_B                1197
#define IDC_END_BLEND_THRESHOLD         1197
#define IDC_START_BLUR_BLUR_SCALE       1198
#define IDC_START_DARKNESS              1198
#define IDC_END_BLUR_BLUR_SCALE         1199
#define IDC_END_DARKNESS                1199
#define IDC_START_BLUR_BLUR_SCALE_POSITION 1200
#define IDC_START_VISIBLE_ANGLE         1200
#define IDC_END_BLUR_BLUR_SCALE_POSITION 1201
#define IDC_END_VISIBLE_ANGLE           1201
#define IDC_START_BLUR_BLUR_SCALE_ROTATION 1202
#define IDC_END_BLUR_BLUR_SCALE_ROTATION 1203
#define IDC_START_IN_FOCUS_DISTANCE     1204
#define IDC_END_IN_FOCUS_DISTANCE       1205
#define IDC_START_BLUR_CENTER_X         1206
#define IDC_END_BLUR_CENTER_X           1207
#define IDC_START_BLUR_CENTER_Y         1208
#define IDC_END_BLUR_CENTER_Y           1209
#define IDC_START_BLUR_LENGTH           1210
#define IDC_END_BLUR_LENGTH             1211
#define IDC_START_IN_FOCUS_RADIUS       1212
#define IDC_END_IN_FOCUS_RADIUS         1213
#define IDC_START_OUT_FOCUS_RADIUS      1214
#define IDC_END_OUT_FOCUS_RADIUS        1215
#define IDC_START_WARP_SCALE            1216
#define IDC_END_WARP_SCALE              1217
#define IDC_START_WARP_SPEED            1218
#define IDC_START_SPEED                 1218
#define IDC_END_WARP_SPEED              1219
#define IDC_END_SPEED                   1219
#define IDC_START_BLUR_BLUR_CENTER_X    1220
#define IDC_END_BLUR_BLUR_CENTER_X      1221
#define IDC_START_BLUR_BLUR_CENTER_Y    1222
#define IDC_END_BLUR_BLUR_CENTER_Y      1223
#define IDC_START_BLUR_BLUR_LENGTH      1224
#define IDC_END_BLUR_BLUR_LENGTH        1225
#define IDC_START_BLUR_IN_FOCUS_RADIUS  1226
#define IDC_END_BLUR_IN_FOCUS_RADIUS    1227
#define IDC_START_BLUR_OUT_FOCUS_RADIUS 1228
#define IDC_END_BLUR_OUT_FOCUS_RADIUS   1229
#define IDC_USE_SQUAD                   1230
#define IDC_START_FACTOR                1231
#define IDC_END_FACTOR                  1232
#define IDC_TEX1_FILE_NAME              1233
#define IDC_BUTTON_TEX1_IMPORT          1234
#define IDC_SKIN_FILE_NAME              1235
#define IDC_BUTTON_SKIN_IMPORT          1236
#define IDC_START_DEPTH_RANGE           1237
#define IDC_END_DEPTH_RANGE             1238
#define IDC_START_BLOOM_SCALE           1239
#define IDC_END_BLOOM_SCALE             1240
#define IDC_START_BLOOM_THRESHOLD       1241
#define IDC_END_BLOOM_THRESHOLD         1242
#define IDC_BUTTON_CHOOSE_START_COLOR   1243
#define IDC_BUTTON_CHOOSE_END_COLOR     1244
#define IDC_QTE_ID                      1244
#define IDC_QTE_SPEED                   1245
#define IDC_ENABLE_MASK                 1246
#define IDC_MASK_FILE_NAME              1247
#define IDC_BUTTON_MASK_IMPORT          1248
#define IDC_EDIT_FRAME                  1249
#define IDC_BUTTON_GO_FRAME             1250
#define IDC_BUTTON_SET_OFFSET_OK        1251
#define IDC_BUTTON_SET_OFFSET_CANCEL    1252
#define ID_FILE_IMPORT_WORLD            10000
#define ID_ANIMATION_PLAY               32771
#define ID_ANIMATION_STOP               32773
#define ID_ANIMATION_RESET              32774
#define ID_ANIMATION_PAUSE              32775
#define ID_OBJECT_ROTATION              32776
#define ID_OBJECT_TRANSLATION           32777
#define ID_OBJECT_UPDOWN                32778
#define ID_NEW_BEZIER                   32779
#define ID_REMOVE_BEZIER_POINT          32780
#define ID_ADD_BEZIER_POINT             32782
#define ID_BEZIER_STATE                 32783
#define ID_SELECTION                    32784
#define ID_TRANSLATION                  32785
#define ID_UPDOWN                       32786
#define ID_ROTATION                     32787
#define ID_ADD_BEZIER_POINT_WITH_NOW_CAMERA 32788
#define ID_ADD_BEZIER_POINT_WITH_NOW_MODEL 32789
#define ID_TRANSLATION_TERRAIN          32790
#define ID_FIX_BEZIER_POINT_WITH_NOW_CAMERA 32791
#define ID_ANIMATION_START_TIME         32792
#define ID_ANIMATION_END_TIME           32793
#define ID_ANIMATION_RESET_TIME         32794
#define ID_DISABLE_CAMERA_ANIMATION     32795
#define ID_OBJECT_LIST                  32796
#define ID_TRACK_PANEL                  32797
#define ID_MODEL_TO_CAMERA              32799
#define ID_SHOW_FPS                     32800
#define ID_MOVE_BEZIER                  32802
#define ID_BIND_CAMERA_TO_OBJECT        32803
#define ID_BIND_CAMERA_OFFSET           32804
#define ID_ACTION_COPY                  32805
#define ID_ACTION_PASTE                 32806
#define ID_ACTION_DELETE                32807
#define ID_MOVE_ACTIONS                 32808
#define ID_VIEW_OPERATOR                32809
#define ID_CALCULATE_TOTAL_TIME         32809
#define ID_ROTATION_TERRAIN             32810
#define ID_FIX_BEZIER_WITH_NOW_CAMERA   32811
#define ID_CHANNEL_COPY                 32814
#define ID_CHANNEL_PASTE                32815
#define ID_FIX_BEZIER_POINT_WITH_NOW_MODEL 32816
#define ID_IMPORT_ACTION_GROUP          32819
#define ID_EXPORT_ACTION_GROUP          32820
#define ID_SHOW_AABB                    32824
#define ID_SHOW_WIRE                    32826
#define ID_BUTTON_WORLD_OFFSET          32828
#define ID_32829                        32829
#define ID_REBUILD_AUDIO                32830

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32831
#define _APS_NEXT_CONTROL_VALUE         1253
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
