/*
 * FILE: EC_WorldFile.h
 *
 * DESCRIPTION: 
 *
 * CREATED BY: Duyuxin, 2004/10/14
 *
 * HISTORY: 
 *
 * Copyright (c) 2004 Archosaur Studio, All Rights Reserved.
 */

#pragma once

#include "ABaseDef.h"

/*	Element world file format:

	Version 19:
	
		ECWDFILEHEADER					| file header
		--------------------------------|
		ECWDFFTWATERVERSION				| fft water param ver.19 +
		--------------------------------|
		iNumBlock * DWORD				| each block data's offset in file
		--------------------------------|
		TRN2FILEBLOCK #0				| Data of each block.
		block #0 data					| Note: Don't assume block data is ordered
		...								|   by their indices.
		TRN2FILEBLOCK #n				|
		block #n data					|
		--------------------------------|
		Tree type data					|
		--------------------------------|
		Grass type data					|
		--------------------------------|
*/

///////////////////////////////////////////////////////////////////////////
//	
//	Define and Macro
//	
///////////////////////////////////////////////////////////////////////////

//	Identity and version of element client world file
#define	ECWDFILE_IDENTIFY	(('E'<<24) | ('C'<<16) | ('W'<<8) | 'D')
#define ECWDFILE_VERSION	19

/*	Identity and version of element client world block shared data file

	Version history:

	v14: - change box area data, new struct ECBSDFILEBOXAREA14;
		 - new struct ECBSDFILETIME;
*/
#define	ECBSDFILE_IDENTIFY	(('B'<<24) | ('S'<<16) | ('D'<<8) | 'F')
#define ECBSDFILE_VERSION	23 // ver.23 : New Post-Effect Param(Color-Correct)

//	Version of element client world mass data file
#define ECWDDTFILE_VERSION	2

//	World file flags
enum
{
	ECWFFLAG_EDITOREXP = 0,		//	File was generated by ElementEditor
	ECWFFLAG_HOMEEXP,			//	File was generated by in-game Home editor
};

#define ECWDFFTWATERVERSION 1

///////////////////////////////////////////////////////////////////////////
//	
//	Types and Global variables
//	
///////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////
//	
//	Declare of Global functions
//	
///////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////
//	
//	World file structures
//	
///////////////////////////////////////////////////////////////////////////

//	File header
struct ECWDFILEHEADER
{
	DWORD	dwIdentify;		//	Identity, must be ECWDFILE_IDENTIFY
	DWORD	dwVersion;		//	Version, must be ECWDFILE_VERSION
	float	fWorldWid;		//	World width in meters
	float	fWorldLen;		//	World length in meters
	float	fBlockSize;		//	Block size in meters
	int		iBlockGrid;		//	Block grid row and column number, each block has (grid x grid) terrain grids
	int		iNumBlock;		//	Number of block
	int		iWorldBlkRow;	//	Block row number in whole world
	int		iWorldBlkCol;	//	Block column number in whole world
	DWORD	dwTreeOff;		//	Tree type data offset
	DWORD	dwGrassOff;		//	Grass type data offset
	int		iNumTreeType;	//	Number of tree type
	int		iNumGrassType;	//	Number of grass type
	DWORD	dwFlags;		//	World file flags
	BYTE	aReserved[60];	//	Reserved
};

//	Block information when ECWDFILE_VERSION <= 3
struct ECWDFILEBLOCK
{
	WORD	iRowInWorld;	//	Row of this block in whole world
	WORD	iColInWorld;	//	Column of this block in whole world
	int		iNumTree;		//	Number of tree
	int		iNumWater;		//	Number of water
	int		iNumGrass;		//	Number of grass type
	int		iNumOrnament;	//	Number of ornament objects
	int		iNumBoxArea;	//	Number of box area
};

//	Block information when 4 <= ECWDFILE_VERSION < 7
struct ECWDFILEBLOCK4
{
	WORD	iRowInWorld;	//	Row of this block in whole world
	WORD	iColInWorld;	//	Column of this block in whole world
	int		iNumTree;		//	Number of tree
	int		iNumWater;		//	Number of water
	int		iNumGrass;		//	Number of grass type
	int		iNumOrnament;	//	Number of ornament objects
	int		iNumBoxArea;	//	Number of box area
	int		iNumEffect;		//	Number of GFX effect
	int		iNumECModel;	//	Number of EC model
	int		iNumCritter;	//	Number of Critter group
};

//	Block information when 7 <= ECWDFILE_VERSION < 9
struct ECWDFILEBLOCK7
{
	WORD	iRowInWorld;	//	Row of this block in whole world
	WORD	iColInWorld;	//	Column of this block in whole world
	int		iNumTree;		//	Number of tree
	int		iNumWater;		//	Number of water
	int		iNumGrass;		//	Number of grass type
	int		iNumOrnament;	//	Number of ornament objects
	int		iNumBoxArea;	//	Number of box area
	int		iNumEffect;		//	Number of GFX effect
	int		iNumECModel;	//	Number of EC model
	int		iNumCritter;	//	Number of Critter group
	int		iNumBezier;		//	Number of bezier route
};

//	Block information when ECWDFILE_VERSION >= 9
struct ECWDFILEBLOCK9
{
	WORD	iRowInWorld;	//	Row of this block in whole world
	WORD	iColInWorld;	//	Column of this block in whole world
	int		iNumTree;		//	Number of tree
	int		iNumWater;		//	Number of water
	int		iNumGrass;		//	Number of grass type
	int		iNumOrnament;	//	Number of ornament objects
	int		iNumBoxArea;	//	Number of box area
	int		iNumEffect;		//	Number of GFX effect
	int		iNumECModel;	//	Number of EC model
	int		iNumCritter;	//	Number of Critter group
	int		iNumBezier;		//	Number of bezier route
	int		iNumSound;		//	Number of sound object
};

//	Block information when ECWDFILE_VERSION >= 16
struct ECWDFILEBLOCK16
{
	WORD	iRowInWorld;	//	Row of this block in whole world
	WORD	iColInWorld;	//	Column of this block in whole world
	int		iNumTree;		//	Number of tree
	int		iNumWater;		//	Number of water
	int		iNumGrass;		//	Number of grass type
	int		iNumOrnament;	//	Number of ornament objects
	int		iNumBoxArea;	//	Number of box area
	int		iNumEffect;		//	Number of GFX effect
	int		iNumECModel;	//	Number of EC model
	int		iNumCritter;	//	Number of Critter group
	int		iNumBezier;		//	Number of bezier route
	int		iNumSound;		//	Number of sound object
	float   fMaxLoadRadius; //  Radius of load
};

//	Block information when ECWDFILE_VERSION >= 17
struct ECWDFILEBLOCK17
{
	WORD	iRowInWorld;	//	Row of this block in whole world
	WORD	iColInWorld;	//	Column of this block in whole world
	int		iNumTree;		//	Number of tree
	int		iNumWater;		//	Number of water
	int		iNumGrass;		//	Number of grass type
	int		iNumOrnament;	//	Number of ornament objects
	int		iNumBoxArea;	//	Number of box area
	int		iNumEffect;		//	Number of GFX effect
	int		iNumECModel;	//	Number of EC model
	int		iNumCritter;	//	Number of Critter group
	int		iNumBezier;		//	Number of bezier route
	int		iNumSound;		//	Number of sound object
	int		iNumMirror;		//	Number of mirror-plane object
	float   fMaxLoadRadius; //  Radius of load
};

//	Block information when ECWDFILE_VERSION >= 18
struct ECWDFILEBLOCK18
{
	WORD	iRowInWorld;	//	Row of this block in whole world
	WORD	iColInWorld;	//	Column of this block in whole world
	int		iNumTree;		//	Number of tree
	int		iNumWater;		//	Number of water
	int		iNumGrass;		//	Number of grass type
	int		iNumOrnament;	//	Number of ornament objects
	int		iNumBoxArea;	//	Number of box area
	int		iNumEffect;		//	Number of GFX effect
	int		iNumECModel;	//	Number of EC model
	int		iNumCritter;	//	Number of Critter group
	int		iNumBezier;		//	Number of bezier route
	int		iNumSound;		//	Number of sound object
	int		iNumMirror;		//	Number of mirror-plane object
	float   fMaxLoadRadius; //  Radius of load
	DWORD	iPostEftOffset; //  Post-effect data offset in block-shared-data file
};

//	Tree information when ECWDFILE_VERSION < 5
struct ECWDFILETREE
{
	DWORD	dwType;			//	Tree type ID
	float	vPos[2];		//	Tree position on x and z axis
};

//	Tree information when ECWDFILE_VERSION >= 5
struct ECWDFILETREE5
{
	DWORD	dwType;			//	Tree type ID
	float	vPos[3];		//	Tree position on x and z axis
};

//	Reference to data in BSD file
struct ECWDFILEDATAREF
{
	DWORD	dwExportID;		//	Object export ID
	DWORD	dwOffset;		//	Data offset in BSD file
};

//	Ornament information when ECWDFILE_VERSION <= 3
struct ECWDFILEORNAMENT
{
	DWORD	dwExportID;		//	Export ID
	float	vPos[3];		//	Position
	float	vDir[3];		//	Orientation
	float	vUp[3];			//	Up direction
	bool	bReflect;		//	Reflect flag
	bool	bRefract;		//	Refract flag
};

//	Grass type data in world file
struct ECWDFILEGRASSTYPE
{
	bool	bAlphaBlend;	//	Flag indicates whether this kind of grass use alpha blend
	int		iAlphaRef;		//	If not using alpha blend, we use alpha compare, this is the reference alpha value (0~255)
	float	fSize;			//	Size scale of this type of grass
	float	fSizeVar;		//	Size varation (0.0~1.0)
	float	fSoftness;		//	Softness for wind effect 0.0 means very hard to blow, 2.0 means too soft to blow (0.0~2.0)
	float	fSightRange;	//	Sight range of this kind of grass
};

//	Effect data in world file, when ECWDFILE_VERSION < 6
struct ECWDFILEEFFECT
{
	DWORD	dwExportID;		//	Export ID
	float	fScale;			//	GFX scale
	float	vPos[3];		//	Position
	float	vDir[3];		//	Orientation
	float	vUp[3];			//	Up direction
};

//	Effect data in world file, when 6 <= ECWDFILE_VERSION < 8
struct ECWDFILEEFFECT6
{
	DWORD	dwExportID;		//	Export ID
	float	fScale;			//	GFX scale
	float	vPos[3];		//	Position
	float	vDir[3];		//	Orientation
	float	vUp[3];			//	Up direction
	float	fSpeed;			//	Play speed
};

//	Effect data in world file, when 8 <= ECWDFILE_VERSION < 12
struct ECWDFILEEFFECT8
{
	DWORD	dwExportID;		//	Export ID
	float	fScale;			//	GFX scale
	float	vPos[3];		//	Position
	float	vDir[3];		//	Orientation
	float	vUp[3];			//	Up direction
	float	fSpeed;			//	Play speed
	int		iValidTime;		//	0-in daylight; 1-in night; 2: 24-hour
};

//	Effect data in world file, when ECWDFILE_VERSION >= 12
struct ECWDFILEEFFECT12
{
	DWORD	dwExportID;		//	Export ID
	float	fScale;			//	GFX scale
	float	vPos[3];		//	Position
	float	vDir[3];		//	Orientation
	float	vUp[3];			//	Up direction
	float	fSpeed;			//	Play speed
	int		iValidTime;		//	0-in daylight; 1-in night; 2: 24-hour
	float	fAlpha;			//	Alpha value
	bool	bAttenuation;	//	Attenuation flag
};

//	Static EC model data in world file
struct ECWDFILEECMODEL13
{
	DWORD	dwExportID;		//	Export ID
	float	vPos[3];		//	Position
	float	vDir[3];		//	Orientation
	float	vUp[3];			//	Up direction
};

//	Static EC model data in world file
struct ECWDFILEECMODEL
{
	DWORD	dwExportID;		//	Export ID
	float	vPos[3];		//	Position
	float	vDir[3];		//	Orientation
	float	vUp[3];			//	Up direction
	int		nShowType;		//  0, show ecmodel on day; 1, show ecmodel on night; 2, show ecmodel at all time
};

//	Sound object data in world file, when ECWDFILE_VERSION < 10
struct ECWDFILESOUND
{
	DWORD	dwExportID;		//	Export ID
	float	vPos[3];		//	Position
	float	fMinDist;		//	Minimum and maximum distance
	float	fMaxDist;
	int		iGroup;			//	Sound group
};

//	Sound object data in world file, when ECWDFILE_VERSION >= 10 and ECWDFILE_VERSION < 11
struct ECWDFILESOUND10
{
	DWORD	dwExportID;		//	Export ID
	float	vPos[3];		//	Position
	float	fMinDist;		//	Minimum and maximum distance
	float	fMaxDist;
	int		iGroup;			//	Sound group
	int		iValidTime;		//	0-in daylight; 1-in night; 2: 24-hour
};

//	Sound object data in world file, when ECWDFILE_VERSION >= 11
struct ECWDFILESOUND11
{
    DWORD	dwExportID;		//	Export ID
    float	vPos[3];		//	Position
    float	fMinDist;		//	Minimum and maximum distance
    float	fMaxDist;
    int		iGroup;			//	Sound group
    int		iValidTime;		//	0-in daylight; 1-in night; 2: 24-hour
    float   vDir[3];
    int     iInsideConeAngle;
    int     iOutsideConeAngle;
    int     iNormalVolume;
    int     iConeOutsideVolume;
};

//	Sound object data in world file, when ECWDFILE_VERSION >= 11
struct ECWDFILESOUND15
{
	DWORD	dwExportID;		//	Export ID
	float	vPos[3];		//	Position
	float	fMinDist;		//	Minimum and maximum distance
	float	fMaxDist;
	//int		iGroup;			//	Sound group
	int		iValidTime;		//	0-in daylight; 1-in night; 2: 24-hour
	float   vDir[3];
	int     iInsideConeAngle;
	int     iOutsideConeAngle;	
	int     iNormalVolume;
	int     iConeOutsideVolume;
	bool	bDistIsUse;		//是否使用场景编辑器中最小最大距离(默认true),否则使用音频编辑器中的设置
	bool	bAngleIsUse;	//是否使用场景编辑器中内外锥角度(默认true),否则使用音频编辑器中的设置
};

///////////////////////////////////////////////////////////////////////////
//	
//	World block shared data file structures
//	
///////////////////////////////////////////////////////////////////////////

//	World block share data file header
struct ECBSDFILEHEADER
{
	DWORD	dwIdentify;		//	Identity, must be ECWTFILE_IDENTIFY
	DWORD	dwVersion;		//	Version, must be ECWTFILE_VERSION
	int		iNumSubTrn;		//	Number of sub-terrain
	BYTE	aReserved[60];	//	Reserved
};

//	Time info
struct ECBSDFILETIME
{
	int		iYear;			//	正常区间 [1900-2100] -1 代表任意
	int		iMouth;			//	正常取值区间[0,11]  -1 代表任意
	int		iWeek;			//	正常取值区间[0,6]  0 代表星期日 -1 代表任意
	int		iDay;			//	正常取值区间[1,31]  -1 代表任意
	int		iHour;			//	正常取值区间[0,23]  -1 代表任意
	int		iMinute;		//	正常取值区间[0,59]

	void Clear() { iYear = iMouth = iWeek = iDay = iHour = iMinute = -1; }
};

//	Box area information in BSD file. when ECBSDFILE_VERSION < 6
struct ECBSDFILEBOXAREA
{
	int		iDefArea;		//	non-zero, is default area
	float	vPos[3];		//	Area position
	float	vExt[3];		//	Area half extents
	float	vAxisX[3];		//	Area normalized x axis
	float	vAxisY[3];		//	Area normalized y axis
	float	vAxisZ[3];		//	Area normalized z axis
	float   fFogStart;		//	Fog start distance
	float   fFogEnd;		//	Fog end distance
	float   fFogDensity;	//	Fog density
	DWORD   dwFogColor;		//	Fog color
	float   fUWFogStart;	//	Under water fog start
	float   fUWFogEnd;		//	Under water fog end
	float   fUWFogDensity;	//	Under water fog density
	DWORD   dwUWFogCol;		//	Under water fog color
	DWORD	dwAmbient;		//	Ambient color
	DWORD	dwDirLtCol;		//	Directional light color
	float	vSkySpeed[2];	//	Sky moving speed on 2 axises
	DWORD	dwTrnLtScale;	//	Terrain light scale
	DWORD	dwTransTime;	//	Transform time
};

//	Box area information in BSD file. when 6 <= ECBSDFILE_VERSION < 8
struct ECBSDFILEBOXAREA6
{
	int		iDefArea;		//	non-zero, is default area
	DWORD	dwAreaFlags;	//	Area flags
	float	vPos[3];		//	Area position
	float	vExt[3];		//	Area half extents
	float	vAxisX[3];		//	Area normalized x axis
	float	vAxisY[3];		//	Area normalized y axis
	float	vAxisZ[3];		//	Area normalized z axis

	float   fFogStart;		//	Fog start distance in daylight
	float   fFogEnd;		//	Fog end distance in daylight
	float   fFogDensity;	//	Fog density in daylight
	DWORD   dwFogColor;		//	Fog color in daylight
	float   fUWFogStart;	//	Under water fog start
	float   fUWFogEnd;		//	Under water fog end
	float   fUWFogDensity;	//	Under water fog density
	DWORD   dwUWFogCol;		//	Under water fog color
	float	fFogStart_n;	//	Fog start distance in night
	float	fFogEnd_n;		//	Fog end distance in night
	float	fFogDensity_n;	//	Fog density in night
	DWORD	dwFogColor_n;	//	Fog color in night

	float	vLightDir[3];	//	Directional light's direction
	DWORD	dwAmbient;		//	Ambient color in daylight
	DWORD	dwDirLtCol;		//	Directional light color in daylight
	DWORD	dwAmbient_n;	//	Ambient color in night
	DWORD	dwDirLtCol_n;	//	Directional light color in night

	float	vSkySpeed[2];	//	Sky moving speed on 2 axises
	DWORD	dwTrnLtScale;	//	Terrain light scale
	DWORD	dwTransTime;	//	Transform time

	int     iRainSpeed;		//	Rain properties
	float   fRainSize;
	DWORD   dwRainCol;
	int     iSnowSpeed;		//	Snow properties
	float   fSnowSize;
	DWORD   dwSnowCol;
};

//	Box area information in BSD file. when ECBSDFILE_VERSION == 8
struct ECBSDFILEBOXAREA8
{
	int		iDefArea;		//	non-zero, is default area
	DWORD	dwAreaFlags;	//	Area flags
	float	vPos[3];		//	Area position
	float	vExt[3];		//	Area half extents
	float	vAxisX[3];		//	Area normalized x axis
	float	vAxisY[3];		//	Area normalized y axis
	float	vAxisZ[3];		//	Area normalized z axis

	float   fFogStart;		//	Fog start distance in daylight
	float   fFogEnd;		//	Fog end distance in daylight
	float   fFogDensity;	//	Fog density in daylight
	DWORD   dwFogColor;		//	Fog color in daylight
	float   fUWFogStart;	//	Under water fog start
	float   fUWFogEnd;		//	Under water fog end
	float   fUWFogDensity;	//	Under water fog density
	DWORD   dwUWFogCol;		//	Under water fog color
	float	fFogStart_n;	//	Fog start distance in night
	float	fFogEnd_n;		//	Fog end distance in night
	float	fFogDensity_n;	//	Fog density in night
	DWORD	dwFogColor_n;	//	Fog color in night

	float	vLightDir[3];	//	Directional light's direction
	DWORD	dwAmbient;		//	Ambient color in daylight
	DWORD	dwDirLtCol;		//	Directional light color in daylight
	DWORD	dwAmbient_n;	//	Ambient color in night
	DWORD	dwDirLtCol_n;	//	Directional light color in night

	float	vSkySpeed[2];	//	Sky moving speed on 2 axises
	DWORD	dwTrnLtScale;	//	Terrain light scale
	DWORD	dwTransTime;	//	Transform time

	int     iRainSpeed;		//	Rain properties
	float   fRainSize;
	DWORD   dwRainCol;
	int     iSnowSpeed;		//	Snow properties
	float   fSnowSize;
	DWORD   dwSnowCol;

	float	fSunPower;		//	Sun power
	float	fSunPower_n;
};

//	Box area information in BSD file. when ECBSDFILE_VERSION == 9
struct ECBSDFILEBOXAREA9
{
	int		iDefArea;		//	non-zero, is default area
	DWORD	dwAreaFlags;	//	Area flags
	float	vPos[3];		//	Area position
	float	vExt[3];		//	Area half extents
	float	vAxisX[3];		//	Area normalized x axis
	float	vAxisY[3];		//	Area normalized y axis
	float	vAxisZ[3];		//	Area normalized z axis

	float   fFogStart;		//	Fog start distance in daylight
	float   fFogEnd;		//	Fog end distance in daylight
	float   fFogDensity;	//	Fog density in daylight
	DWORD   dwFogColor;		//	Fog color in daylight
	float   fUWFogStart;	//	Under water fog start
	float   fUWFogEnd;		//	Under water fog end
	float   fUWFogDensity;	//	Under water fog density
	DWORD   dwUWFogCol;		//	Under water fog color
	float	fFogStart_n;	//	Fog start distance in night
	float	fFogEnd_n;		//	Fog end distance in night
	float	fFogDensity_n;	//	Fog density in night
	DWORD	dwFogColor_n;	//	Fog color in night

	float	vLightDir[3];	//	Directional light's direction
	DWORD	dwAmbient;		//	Ambient color in daylight
	DWORD	dwDirLtCol;		//	Directional light color in daylight
	DWORD	dwAmbient_n;	//	Ambient color in night
	DWORD	dwDirLtCol_n;	//	Directional light color in night

	float	vSkySpeed[2];	//	Sky moving speed on 2 axises
	DWORD	dwTrnLtScale;	//	Terrain light scale
	DWORD	dwTransTime;	//	Transform time

	int     iRainSpeed;		//	Rain properties
	float   fRainSize;
	DWORD   dwRainCol;
	int     iSnowSpeed;		//	Snow properties
	float   fSnowSize;
	DWORD   dwSnowCol;

	float	fSunPower;		//	Sun power
	float	fSunPower_n;
	DWORD	dwCloudAmb;		//	Clound ambient color
	DWORD	dwCloudDir;		//	Clound direction light color
};

//	Box area information in BSD file. when ECBSDFILE_VERSION == 10
struct ECBSDFILEBOXAREA10
{
	int		iDefArea;		//	non-zero, is default area
	DWORD	dwAreaFlags;	//	Area flags
	float	vPos[3];		//	Area position
	float	vExt[3];		//	Area half extents
	float	vAxisX[3];		//	Area normalized x axis
	float	vAxisY[3];		//	Area normalized y axis
	float	vAxisZ[3];		//	Area normalized z axis

	float   fFogStart;		//	Fog start distance in daylight
	float   fFogEnd;		//	Fog end distance in daylight
	float   fFogDensity;	//	Fog density in daylight
	DWORD   dwFogColor;		//	Fog color in daylight
	float   fUWFogStart;	//	Under water fog start
	float   fUWFogEnd;		//	Under water fog end
	float   fUWFogDensity;	//	Under water fog density
	DWORD   dwUWFogCol;		//	Under water fog color
	float	fFogStart_n;	//	Fog start distance in night
	float	fFogEnd_n;		//	Fog end distance in night
	float	fFogDensity_n;	//	Fog density in night
	DWORD	dwFogColor_n;	//	Fog color in night

	float	vLightDir[3];	//	Directional light's direction
	DWORD	dwAmbient;		//	Ambient color in daylight
	DWORD	dwDirLtCol;		//	Directional light color in daylight
	DWORD	dwAmbient_n;	//	Ambient color in night
	DWORD	dwDirLtCol_n;	//	Directional light color in night

	float	vSkySpeed[2];	//	Sky moving speed on 2 axises
	DWORD	dwTrnLtScale;	//	Terrain light scale
	DWORD	dwTransTime;	//	Transform time

	int     iRainSpeed;		//	Rain properties
	float   fRainSize;
	DWORD   dwRainCol;
	int     iSnowSpeed;		//	Snow properties
	float   fSnowSize;
	DWORD   dwSnowCol;

	float	fSunPower;		//	Sun power
	float	fSunPower_n;
	DWORD	dwCloudAmb;		//	Clound ambient color in daylight
	DWORD	dwCloudDir;		//	Clound direction light color in daylight
	DWORD	dwCloudAmb_n;	//	Clound ambient color in night
	DWORD	dwCloudDir_n;	//	Clound direction light color in night
};

//	Box area information in BSD file. when ECBSDFILE_VERSION >= 11 && < 13
struct ECBSDFILEBOXAREA11
{
	int		iDefArea;		//	non-zero, is default area
	DWORD	dwAreaFlags;	//	Area flags
	float	vPos[3];		//	Area position
	float	vExt[3];		//	Area half extents
	float	vAxisX[3];		//	Area normalized x axis
	float	vAxisY[3];		//	Area normalized y axis
	float	vAxisZ[3];		//	Area normalized z axis

	float   fFogStart;		//	Fog start distance in daylight
	float   fFogEnd;		//	Fog end distance in daylight
	float   fFogDensity;	//	Fog density in daylight
	DWORD   dwFogColor;		//	Fog color in daylight
	float   fUWFogStart;	//	Under water fog start in daylight
	float   fUWFogEnd;		//	Under water fog end in daylight
	float   fUWFogDensity;	//	Under water fog density in daylight
	DWORD   dwUWFogCol;		//	Under water fog color in daylight
	float	fFogStart_n;	//	Fog start distance in night
	float	fFogEnd_n;		//	Fog end distance in night
	float	fFogDensity_n;	//	Fog density in night
	DWORD	dwFogColor_n;	//	Fog color in night

	float	vLightDir[3];	//	Directional light's direction
	DWORD	dwAmbient;		//	Ambient color in daylight
	DWORD	dwDirLtCol;		//	Directional light color in daylight
	DWORD	dwAmbient_n;	//	Ambient color in night
	DWORD	dwDirLtCol_n;	//	Directional light color in night

	float	vSkySpeed[2];	//	Sky moving speed on 2 axises
	DWORD	dwTrnLtScale;	//	Terrain light scale
	DWORD	dwTransTime;	//	Transform time

	int     iRainSpeed;		//	Rain properties
	float   fRainSize;
	DWORD   dwRainCol;
	int     iSnowSpeed;		//	Snow properties
	float   fSnowSize;
	DWORD   dwSnowCol;

	float	fSunPower;		//	Sun power
	float	fSunPower_n;
	DWORD	dwCloudAmb;		//	Clound ambient color in daylight
	DWORD	dwCloudDir;		//	Clound direction light color in daylight
	DWORD	dwCloudAmb_n;	//	Clound ambient color in night
	DWORD	dwCloudDir_n;	//	Clound direction light color in night
	float   fUWFogStart_n;	//	Under water fog start in night
	float   fUWFogEnd_n;	//	Under water fog end in night
	float   fUWFogDensity_n;//	Under water fog density in night
	DWORD   dwUWFogCol_n;	//	Under water fog color in night
};

//	Box area information in BSD file. when ECBSDFILE_VERSION >= 14
struct ECBSDFILEBOXAREA14
{
	int		iDefArea;		//	non-zero, is default area
	DWORD	dwAreaFlags;	//	Area flags
	float	vPos[3];		//	Area position
	float	vExt[3];		//	Area half extents
	float	vAxisX[3];		//	Area normalized x axis
	float	vAxisY[3];		//	Area normalized y axis
	float	vAxisZ[3];		//	Area normalized z axis

	float   fFogStart;		//	Fog start distance in daylight
	float   fFogEnd;		//	Fog end distance in daylight
	float   fFogDensity;	//	Fog density in daylight
	DWORD   dwFogColor;		//	Fog color in daylight
	float   fUWFogStart;	//	Under water fog start in daylight
	float   fUWFogEnd;		//	Under water fog end in daylight
	float   fUWFogDensity;	//	Under water fog density in daylight
	DWORD   dwUWFogCol;		//	Under water fog color in daylight
	float	fFogStart_n;	//	Fog start distance in night
	float	fFogEnd_n;		//	Fog end distance in night
	float	fFogDensity_n;	//	Fog density in night
	DWORD	dwFogColor_n;	//	Fog color in night

	float	vLightDir[3];	//	Directional light's direction
	DWORD	dwAmbient;		//	Ambient color in daylight
	DWORD	dwDirLtCol;		//	Directional light color in daylight
	DWORD	dwAmbient_n;	//	Ambient color in night
	DWORD	dwDirLtCol_n;	//	Directional light color in night

	float	vSkySpeed[2];	//	Sky moving speed on 2 axises
	DWORD	dwTrnLtScale;	//	Terrain light scale
	DWORD	dwTransTime;	//	Transform time

	int     iRainSpeed;		//	Rain properties
	float   fRainSize;
	DWORD   dwRainCol;
	int     iSnowSpeed;		//	Snow properties
	float   fSnowSize;
	DWORD   dwSnowCol;

	float	fSunPower;		//	Sun power
	float	fSunPower_n;
	DWORD	dwCloudAmb;		//	Clound ambient color in daylight
	DWORD	dwCloudDir;		//	Clound direction light color in daylight
	DWORD	dwCloudAmb_n;	//	Clound ambient color in night
	DWORD	dwCloudDir_n;	//	Clound direction light color in night
	float   fUWFogStart_n;	//	Under water fog start in night
	float   fUWFogEnd_n;	//	Under water fog end in night
	float   fUWFogDensity_n;//	Under water fog density in night
	DWORD   dwUWFogCol_n;	//	Under water fog color in night

	//	Version 14
	ECBSDFILETIME	tmBorn;		//	Box area valid time range
	ECBSDFILETIME	tmDie;
};

//	Box area information in BSD file. when ECBSDFILE_VERSION >= 15
struct ECBSDFILEBOXAREA15
{
	int		iDefArea;		//	non-zero, is default area
	DWORD	dwAreaFlags;	//	Area flags
	float	vPos[3];		//	Area position
	float	vExt[3];		//	Area half extents
	float	vAxisX[3];		//	Area normalized x axis
	float	vAxisY[3];		//	Area normalized y axis
	float	vAxisZ[3];		//	Area normalized z axis

	float   fFogStart;		//	Fog start distance in daylight
	float   fFogEnd;		//	Fog end distance in daylight
	float   fFogDensity;	//	Fog density in daylight
	DWORD   dwFogColor;		//	Fog color in daylight
	float   fUWFogStart;	//	Under water fog start in daylight
	float   fUWFogEnd;		//	Under water fog end in daylight
	float   fUWFogDensity;	//	Under water fog density in daylight
	DWORD   dwUWFogCol;		//	Under water fog color in daylight
	float	fFogStart_n;	//	Fog start distance in night
	float	fFogEnd_n;		//	Fog end distance in night
	float	fFogDensity_n;	//	Fog density in night
	DWORD	dwFogColor_n;	//	Fog color in night

	float	vLightDir[3];	//	Directional light's direction
	DWORD	dwAmbient;		//	Ambient color in daylight
	DWORD	dwDirLtCol;		//	Directional light color in daylight
	DWORD	dwAmbient_n;	//	Ambient color in night
	DWORD	dwDirLtCol_n;	//	Directional light color in night

	float	vSkySpeed[2];	//	Sky moving speed on 2 axises
	DWORD	dwTrnLtScale;	//	Terrain light scale
	DWORD	dwTransTime;	//	Transform time

	int     iRainSpeed;		//	Rain properties
	float   fRainSize;
	DWORD   dwRainCol;
	int     iSnowSpeed;		//	Snow properties
	float   fSnowSize;
	DWORD   dwSnowCol;

	float	fSunPower;		//	Sun power
	float	fSunPower_n;
	DWORD	dwCloudAmb;		//	Clound ambient color in daylight
	DWORD	dwCloudDir;		//	Clound direction light color in daylight
	DWORD	dwCloudAmb_n;	//	Clound ambient color in night
	DWORD	dwCloudDir_n;	//	Clound direction light color in night
	float   fUWFogStart_n;	//	Under water fog start in night
	float   fUWFogEnd_n;	//	Under water fog end in night
	float   fUWFogDensity_n;//	Under water fog density in night
	DWORD   dwUWFogCol_n;	//	Under water fog color in night

	//	Version 14
	ECBSDFILETIME	tmBorn;		//	Box area valid time range
	ECBSDFILETIME	tmDie;

	float	fCapTileSpeed; // Cloud repeat count
	float	fCapRotSpeed;  // Cloud rotate speed
};

//	Box area information in BSD file. when ECBSDFILE_VERSION >= 16
struct ECBSDFILEBOXAREA17
{
	int		iDefArea;		//	non-zero, is default area
	DWORD	dwAreaFlags;	//	Area flags
	float	vPos[3];		//	Area position
	float	vExt[3];		//	Area half extents
	float	vAxisX[3];		//	Area normalized x axis
	float	vAxisY[3];		//	Area normalized y axis
	float	vAxisZ[3];		//	Area normalized z axis

	float   fFogStart;		//	Fog start distance in daylight
	float   fFogEnd;		//	Fog end distance in daylight
	float   fFogDensity;	//	Fog density in daylight
	DWORD   dwFogColor;		//	Fog color in daylight
	float   fUWFogStart;	//	Under water fog start in daylight
	float   fUWFogEnd;		//	Under water fog end in daylight
	float   fUWFogDensity;	//	Under water fog density in daylight
	DWORD   dwUWFogCol;		//	Under water fog color in daylight
	float	fFogStart_n;	//	Fog start distance in night
	float	fFogEnd_n;		//	Fog end distance in night
	float	fFogDensity_n;	//	Fog density in night
	DWORD	dwFogColor_n;	//	Fog color in night

	float	vLightDir[3];	//	Directional light's direction
	DWORD	dwAmbient;		//	Ambient color in daylight
	DWORD	dwDirLtCol;		//	Directional light color in daylight
	DWORD	dwAmbient_n;	//	Ambient color in night
	DWORD	dwDirLtCol_n;	//	Directional light color in night

	float	vSkySpeed[2];	//	Sky moving speed on 2 axises
	DWORD	dwTrnLtScale;	//	Terrain light scale
	DWORD	dwTransTime;	//	Transform time

	int     iRainSpeed;		//	Rain properties
	float   fRainSize;
	DWORD   dwRainCol;
	int     iSnowSpeed;		//	Snow properties
	float   fSnowSize;
	DWORD   dwSnowCol;

	float	fSunPower;		//	Sun power
	float	fSunPower_n;
	DWORD	dwCloudAmb;		//	Clound ambient color in daylight
	DWORD	dwCloudDir;		//	Clound direction light color in daylight
	DWORD	dwCloudAmb_n;	//	Clound ambient color in night
	DWORD	dwCloudDir_n;	//	Clound direction light color in night
	float   fUWFogStart_n;	//	Under water fog start in night
	float   fUWFogEnd_n;	//	Under water fog end in night
	float   fUWFogDensity_n;//	Under water fog density in night
	DWORD   dwUWFogCol_n;	//	Under water fog color in night

	//	Version 14
	ECBSDFILETIME	tmBorn;		//	Box area valid time range
	ECBSDFILETIME	tmDie;

	float	fCapTileSpeed; // Cloud repeat count
	float	fCapRotSpeed;  // Cloud rotate speed

	int		nPriority; //优先级别越小越高
};

//	Box area information in BSD file. when ECBSDFILE_VERSION >= 19
struct ECBSDFILEBOXAREA19
{
	int		iDefArea;		//	non-zero, is default area
	DWORD	dwAreaFlags;	//	Area flags
	float	vPos[3];		//	Area position
	float	vExt[3];		//	Area half extents
	float	vAxisX[3];		//	Area normalized x axis
	float	vAxisY[3];		//	Area normalized y axis
	float	vAxisZ[3];		//	Area normalized z axis

	float   fFogStart;		//	Fog start distance in daylight
	float   fFogEnd;		//	Fog end distance in daylight
	float   fFogDensity;	//	Fog density in daylight
	DWORD   dwFogColor;		//	Fog color in daylight
	float   fUWFogStart;	//	Under water fog start in daylight
	float   fUWFogEnd;		//	Under water fog end in daylight
	float   fUWFogDensity;	//	Under water fog density in daylight
	DWORD   dwUWFogCol;		//	Under water fog color in daylight
	float	fFogStart_n;	//	Fog start distance in night
	float	fFogEnd_n;		//	Fog end distance in night
	float	fFogDensity_n;	//	Fog density in night
	DWORD	dwFogColor_n;	//	Fog color in night

	float	vLightDir[3];	//	Directional light's direction
	DWORD	dwAmbient;		//	Ambient color in daylight
	DWORD	dwDirLtCol;		//	Directional light color in daylight
	DWORD	dwAmbient_n;	//	Ambient color in night
	DWORD	dwDirLtCol_n;	//	Directional light color in night

	float	vSkySpeed[2];	//	Sky moving speed on 2 axises
	DWORD	dwTrnLtScale;	//	Terrain light scale
	DWORD	dwTransTime;	//	Transform time

	int     iRainSpeed;		//	Rain properties
	float   fRainSize;
	DWORD   dwRainCol;
	int     iSnowSpeed;		//	Snow properties
	float   fSnowSize;
	DWORD   dwSnowCol;

	float	fSunPower;		//	Sun power
	float	fSunPower_n;
	DWORD	dwCloudAmb;		//	Clound ambient color in daylight
	DWORD	dwCloudDir;		//	Clound direction light color in daylight
	DWORD	dwCloudAmb_n;	//	Clound ambient color in night
	DWORD	dwCloudDir_n;	//	Clound direction light color in night
	float   fUWFogStart_n;	//	Under water fog start in night
	float   fUWFogEnd_n;	//	Under water fog end in night
	float   fUWFogDensity_n;//	Under water fog density in night
	DWORD   dwUWFogCol_n;	//	Under water fog color in night

	//	Version 14
	ECBSDFILETIME	tmBorn;		//	Box area valid time range
	ECBSDFILETIME	tmDie;

	float	fCapTileSpeed; // Cloud repeat count
	float	fCapRotSpeed;  // Cloud rotate speed

	int		nPriority; //优先级别越小越高

	// Version 19	
	float   fGlbFogHeightStart;
	float   fGlbFogHeightEnd;
	float   fGlbFogDensityStart;
	float   fGlbFogDensityEnd;
	float   fGlbFogHeightStartNight;
	float   fGlbFogHeightEndNight;
	float	fGlbFogDensityStartNight;
	float   fGlbFogDensityEndNight;

	DWORD	dwAmbient2;		//	垂直的环境光
	DWORD	dwAmbient2_n;	//	垂直的环境光
};

//	Box area information in BSD file. when ECBSDFILE_VERSION >= 20
struct ECBSDFILEBOXAREA20
{
	int		iDefArea;		//	non-zero, is default area
	DWORD	dwAreaFlags;	//	Area flags
	float	vPos[3];		//	Area position
	float	vExt[3];		//	Area half extents
	float	vAxisX[3];		//	Area normalized x axis
	float	vAxisY[3];		//	Area normalized y axis
	float	vAxisZ[3];		//	Area normalized z axis

	float   fFogStart;		//	Fog start distance in daylight
	float   fFogEnd;		//	Fog end distance in daylight
	float   fFogDensity;	//	Fog density in daylight
	DWORD   dwFogColor;		//	Fog color in daylight
	float   fUWFogStart;	//	Under water fog start in daylight
	float   fUWFogEnd;		//	Under water fog end in daylight
	float   fUWFogDensity;	//	Under water fog density in daylight
	DWORD   dwUWFogCol;		//	Under water fog color in daylight
	float	fFogStart_n;	//	Fog start distance in night
	float	fFogEnd_n;		//	Fog end distance in night
	float	fFogDensity_n;	//	Fog density in night
	DWORD	dwFogColor_n;	//	Fog color in night

	float	vLightDir[3];	//	Directional light's direction
	DWORD	dwAmbient;		//	Ambient color in daylight
	DWORD	dwDirLtCol;		//	Directional light color in daylight
	DWORD	dwAmbient_n;	//	Ambient color in night
	DWORD	dwDirLtCol_n;	//	Directional light color in night

	float	vSkySpeed[2];	//	Sky moving speed on 2 axises
	DWORD	dwTrnLtScale;	//	Terrain light scale
	DWORD	dwTransTime;	//	Transform time

	int     iRainSpeed;		//	Rain properties
	float   fRainSize;
	DWORD   dwRainCol;
	int     iSnowSpeed;		//	Snow properties
	float   fSnowSize;
	DWORD   dwSnowCol;

	float	fSunPower;		//	Sun power
	float	fSunPower_n;
	DWORD	dwCloudAmb;		//	Clound ambient color in daylight
	DWORD	dwCloudDir;		//	Clound direction light color in daylight
	DWORD	dwCloudAmb_n;	//	Clound ambient color in night
	DWORD	dwCloudDir_n;	//	Clound direction light color in night
	float   fUWFogStart_n;	//	Under water fog start in night
	float   fUWFogEnd_n;	//	Under water fog end in night
	float   fUWFogDensity_n;//	Under water fog density in night
	DWORD   dwUWFogCol_n;	//	Under water fog color in night

	//	Version 14
	ECBSDFILETIME	tmBorn;		//	Box area valid time range
	ECBSDFILETIME	tmDie;

	float	fCapTileSpeed; // Cloud repeat count
	float	fCapRotSpeed;  // Cloud rotate speed

	int		nPriority; //优先级别越小越高

	// Version 19	
	float   fGlbFogHeightStart;
	float   fGlbFogHeightEnd;
	float   fGlbFogDensityStart;
	float   fGlbFogDensityEnd;
	float   fGlbFogHeightStartNight;
	float   fGlbFogHeightEndNight;
	float	fGlbFogDensityStartNight;
	float   fGlbFogDensityEndNight;

	DWORD	dwAmbient2;		//	垂直的环境光
	DWORD	dwAmbient2_n;	//	垂直的环境光

	// Version 20
	DWORD   dwFogColor2;
	float   fFogColorDensityStart;
	float   fFogColorDensityEnd;
	float   fFogHorzeDensity;
	float   fFogHorzePower;

	DWORD   dwFogColor2Night;
	float   fFogColorDensityStartNight;
	float   fFogColorDensityEndNight;
	float   fFogHorzeDensityNight;
	float   fFogHorzePowerNight;
};

//	Grass area information in BSD file. ECBSDFILE_VERSION < 7
struct ECBSDFILEGRASS
{
	DWORD	dwTypeID;		//	Grass type ID
	float	vPos[3];		//	Grass area center
	float	fGridSize;		//	Grid size
	int		iGridCol;		//	Grid column number
	int		iGridRow;		//	Grid row number
};

//	Grass area information in BSD file. ECBSDFILE_VERSION >= 7
struct ECBSDFILEGRASS7
{
	DWORD	dwTypeID;		//	Grass type ID
	float	vPos[3];		//	Grass area center
	float	fGridSize;		//	Grid size
	int		iGridCol;		//	Grid column number
	int		iGridRow;		//	Grid row number
	int		iSubTerrain;	//	Index of sub-terrain
	int		iDataIndex;		//	Index in sub-terrain's data file
};

//	Water area information in BSD file. ECBSDFILE_VERSION >= 7
struct ECBSDFILEWATER
{
	int		iSubTerrain;	//	Index of sub-terrain
	int		iDataIndex;		//	Index in sub-terrain's data file
};

//	Critter group information in BSD file. 4 <= ECBSDFILE_VERSION < 5
struct ECBSDFILECRITTER
{
	int		iCritterType;	//	Critter type
	float	vPos[3];		//	Action area center
	float	fRadius;		//	Action radious
	int		iCount;			//	Number of critter
	int		iBehaviour;		//	Behaviour type
};

//	Critter group information in BSD file. ECBSDFILE_VERSION >= 5
struct ECBSDFILECRITTER5
{
	int		iCritterType;	//	Critter type
	float	vPos[3];		//	Action area center
	float	fRadius;		//	Action radious
	int		iCount;			//	Number of critter
	int		iBehaviour;		//	Behaviour type
	DWORD	dwBezier;		//	ID of bezier route
	float	fSpeed;			//	Moving speed
};

//	Ornament information in BSD file. 4 <= ECBSDFILE_VERSION < 13
struct ECBSDFILEORNAMENT
{
	float	vPos[3];		//	Position
	float	vDir[3];		//	Orientation
	float	vUp[3];			//	Up direction
	bool	bReflect;		//	Reflect flag
	bool	bRefract;		//	Refract flag
};

//	Ornament information in BSD file. ECBSDFILE_VERSION >= 13
struct ECBSDFILEORNAMENT13
{
	float	vPos[3];		//	Position
	float	vDir[3];		//	Orientation
	float	vUp[3];			//	Up direction
	bool	bReflect;		//	Reflect flag
	bool	bRefract;		//	Refract flag
	bool	bOptimize;		//	Optimize flag
};

//	Ornament information in BSD file. ECBSDFILE_VERSION >= 13
struct ECBSDFILEORNAMENT16
{
	float	vPos[3];		//	Position
	float	vDir[3];		//	Orientation
	float	vUp[3];			//	Up direction
	bool	bReflect;		//	Reflect flag
	bool	bRefract;		//	Refract flag
	bool	bOptimize;		//	Optimize flag
	int		iFeetSound;		//  Building's feet sound
};

// Mirror plane in block-shared-data file.
struct ECBSDFILEMIRRORPLANE
{
	float	vPos[3];		//	Position
	float	vDir[3];		//	Orientation
	float	vUp[3];			//	Up direction
	float	vScl[3];		//	Scale
	// parameters in CMirrorPlaneObject
	float	m_fPlaneWidth;					// Plane size along X axis
	float	m_fPlaneHeight;					// Plane size along Z axis
	UINT	m_nNumSegmentsX;				// Number of segments of the mesh along X axis
	UINT	m_nNumSegmentsY;				// Number of segments of the mesh along Y axis
	float	m_fAlphaMaskValue;				// The comparison value for alpha mask. ( If the alpha value of given pixel on the alpha mask texture less than this value, it will be clipped. )
	float	m_fUVOffsetMultipler;			// UV offset multipler applied to noise UV
	float	m_fFakeReflectPower;			// Power of fake reflection.
	int		m_nLitBakingMode;				// Indicates whether this object use pre-baked vertex color or light maps.
	int		m_nAutoLightmapSize;
	int     m_nCustomLightmapSize;
	float	m_fLitDirectScale;
	float	m_fLitIndirectScale;
	float	m_fLitAOScale;
};

///////////////////////////////////////////////////////////////////////////
//	
//	World mass data file structures
//	
///////////////////////////////////////////////////////////////////////////

//	File header
struct ECWDDTFILEHEADER
{
	DWORD	dwVersion;		//	Version, must be ECWTFILE_VERSION
	bool	bCompress;		//	Compress flag
};

//	Data chunk description
struct ECWDDTFILECHUNK
{
	DWORD	dwCompSize;		//	Data size after compressed
	DWORD	dwOriginSize;	//	Original data size
};

struct ECWDFILEFFTWATER // FFT water param in file when ECWDFILE_VERSION >= 19
{
	float m_fWaterLevel;				//水面高度
	float m_fWindDirection;				//风向								0 ~ PI*2
	float m_fGravity;					//重力								1 ~ 20

	float m_fWindSpeed;					//风速								0 ~ 16
	float m_fWavesSpeed;				//波浪速度(影响非FFT波浪和泡沫)		0 ~ 10 
	float m_fWavesAmount;				//FFT瓷砖大小						0 ~ 10
	float m_fWavesSize;					//波浪剧烈程度						0 ~ 2
	float m_fSoftIntersectionFactor;	//边缘软化程度						0 ~ 10
	float m_fReflectionAmount;			//反射强度							0 ~ 10
	float m_fWhiteCapsAmount;			//顶部高光							0 ~ 2
	float m_fSunMultiplier;				//太阳反光强度						0 ~ 32
	float m_fFresnelScale;				//菲涅尔缩放						0 ~ 32

	float m_fFogDensity;				//水下雾强度系数					0 ~ 4
	float m_fWaterFogScaleExp;			//水下雾强度指数					0 ~ 10				

	bool m_bUseFFT;						//是否开启FFT
	bool m_bEdgeFoam;					//是否开启边缘泡沫
	bool m_bWaveFoam;					//是否开启波浪上的泡沫
	bool m_bWaveGloss;					//是否开启波浪上的高光

	bool m_bUseCustomColor;				//是否使用用户指定的颜色作为水的颜色, 不开启则使用全局雾的颜色
	A3DVECTOR3 m_vWaterFogColor;		//用户指定的水颜色

	bool m_bEnableAreaConstrain;
	A3DVECTOR4 m_vAreaConstrain;
	bool m_bCubeReflect;
};