

-- 系统菜单
System_Bar =
{
     {
      	name   = _t"人物",
      	label  = "Label_Roleinfo",
      	radio  = "Radio_Roleinfo",
      	bg	   = "Edit_Roleinfo",
		jump = 1,
        sub_button_id = {2,37,44,50,54,56,57},
     },
     {
      	name   = _t"物品",
      	label  = "Label_Item",
      	radio  = "Radio_Item",
      	bg	   = "Edit_Item",
		jump = 4,
        sub_button_id = {6,7,8,55},
     },
     {
      	name   = _t"技能",
      	label  = "Label_Skills",
      	radio  = "Radio_Skills",
      	bg	   = "Edit_Skills",
		jump = 37,
        sub_button_id = {4,10,11},
     },
     {
      	name   = _t"任务",
      	label  = "Label_Experience",
      	radio  = "Radio_Experience",
      	bg	   = "Edit_Experience",
		jump = 5,
        sub_button_id = {14,15,34,38,45},
     },
     {
      	name   = _t"社交",
      	label  = "Label_Society",
      	radio  = "Radio_Society",
      	bg	   = "Edit_Society",
		jump = 10,
        sub_button_id = {18,51,19,20,3,46,48},
     },
     {
      	name   = _t"称号",
      	label  = "Label_Collect",
      	radio  = "Radio_Collect",
      	bg	   = "Edit_Collect",
		jump = 28,
        sub_button_id = {21,23,24},
     },
     {
      	name   = _t"商城",
      	label  = "Label_Star",
      	radio  = "Radio_Star",
      	bg	   = "Edit_Star",
		jump = 2,
        sub_button_id = {26,33,49},
     },
     {
      	name   = _t"防卡",
      	label  = "Label_Quick",
      	radio  = "Radio_Quick",
      	bg	   = "Edit_Quick",
		jump = 49,
        sub_button_id = {39,41,42,43,52},
     },
     {
      	name   = _t"系统",
      	label  = "Label_System",
      	radio  = "Radio_System",
      	bg	   = "Edit_System",
		jump = 17,
		sub_button_id = {30,32,31,35,36,47},
     },
}

--二级系统菜单
System_Bar_Sub =
{
	[2] = {
				name = _t"宇宙",
				button = "Button_Cosmos",
				label = "Label_Cosmos",
				key	  = "Label_CosmosHotKeyBG",
				jump = 8,
				image = "systembarNew\\Button_attributeUp.png",
		   },
	[3] = {
				name = _t"宠物",
				button = "Button_Pet",
				label = "Label_Pet",
				key	  = "Label_PetHotKeyBG",
				jump = 16,
		   },
	[4] =  {
				name = _t"斗魂",
				button = "Button_Talent",
				label = "Label_Talent",
				key = "Label_TalentHotKeyBG",
				jump = 25,
			},
	[6] = {
				name = _t"圣衣",
				button = "Button_SaintCloth",
				label = "Label_SaintCloth",
				key	  = "Label_SaintClothHotKeyBG",
				jump = 9,
		  },
	[7] = {
				name = _t"魔盒",
				button = "Button_Magicbox",
				label = "Label_Magicbox",
				key	  = "Label_MagicboxHotKeyBG",
				jump = 35,
		  },
	[8] = {
				name = _t"摆摊",
				button = "Button_Stall",
				label = "Label_Stall",
				key	  = "Label_StallHotKeyBG",
				jump  = 36,
		   },
	[10] = {
			 	name = _t"连招",
			 	button = "Button_Sequence",
			 	label = "Label_Sequence",
			 	key	  = "Label_SequenceHotKeyBG",
			 	jump = 27,
			},
	[11] = {
			 	name = _t"生产",
			 	button = "Button_Produce",
			 	label = "Label_Produce",
			 	key	  = "Label_ProduceHotKeyBG",
				jump = 38,
			 },
	[14] = {
				name = _t"组队",
				button = "Button_Team",
				label = "Label_Team",
			 	key	  = "Label_TeamHotKeyBG",
				jump = 14,
			},
	[15] = {
				name = _t"活动",
				button = "Button_Daily",
				label = "Label_Daily",
			 	key	  = "Label_DailyHotKeyBG",
				jump = 39,
			},
	[18] = {
				name = _t"好友",
				button = "Button_Friend",
				label = "Label_Friend",
			 	key	  = "Label_FriendHotKeyBG",
			 	jump = 10,
			},
	[19] = {
				name = _t"军团",
				button = "Button_Army",
				label = "Label_Army",
			 	key	  = "Label_ArmyHotKeyBG",
				jump = 12,
			},
	[20] = {
				name = _t"排行榜",
				button = "Button_Top",
				label = "Label_Top",
			 	key	  = "Label_TopHotKeyBG",
				jump = 13,
			},

	[21] = {
				name = _t"成就",
				button = "Button_Achi",
				label = "Label_Achi",
			 	key	  = "Label_AchiHotKeyBG",
			 	jump = 23,
			},
	[23] = {
				name = _t"图鉴",
				button = "Button_PhotoBook",
				label = "Label_PhotoBook",
			 	key	  = "Label_PhotoBookHotKeyBG",
			 	jump = 22,
			},
	[24] = {
				name = _t"声望",
				button = "Button_Prestige",
				label = "Label_Prestige",
			 	key	  = "Label_PrestigeHotKeyBG",
			 	jump = 24,
			},
	[26] = {
				name = _t"珍宝",
				button = "Button_Treasure",
				label = "Label_Treasure",
			 	key	  = "Label_TreasureHotKeyBG",
				jump = 40,
			},
	[30] = {
				name = "IE",
				button = "Button_Ie",
				label = "Label_Ie",
			 	key	  = "Label_IeHotKeyBG",
				jump = 32,
			},
	[31] = {
				name = _t"安全锁",
				button = "Button_Lock",
				label = "Label_Lock",
			 	key	  = "Label_LockHotKeyBG",
				jump = 29,
			},
	[32] = {
				name = "PK",
				button = "Button_Pk",
				label = "Label_Pk",
			 	key	  = "Label_PkHotKeyBG",
				jump = 31,
			},
	[33] = {
				name = "VIP",
				button = "Button_VIP",
				label = "Label_VIP",
			 	key	  = "Label_VIPHotKeyBG",
				jump  = 41,
			},
	[34] = {
				name = _t"体检",
				button = "Button_Guide",
				label = "Label_Guide",
			 	key	  = "Label_GuideHotKeyBG",
			 	jump  = 57,
			},
	[35] = {
				name = _t"百科",
				button = "Button_Wiki",
				label = "Label_Wiki",
			 	key	  = "Label_WikiHotKeyBG",
			 	jump  = 33,
			},
	[36] = {
				name = _t"拍照",
				button = "Button_Photo",
				label = "Label_Photo",
			 	key	  = "Label_PhotoHotKeyBG",
			 	jump  = 42,
			},
	[37] = {
				name = _t"守护",
				button = "Button_CombatPet",
				label = "Label_CombatPet",
			 	key	  = "Label_CombatPetHotKeyBG",
			 	jump  = 43,
			},
	[38] = {
				name = _t"进程",
				button = "Button_ServerPrg",
				label = "Label_ServerPrg",
			 	key	  = "Label_ServerPrgHotKeyBG",
			 	jump  =	44,
			},
	[39] = {
				name = _t"交谈",
				button = "Button_Quick1",
				label = "Label_Quick1",
			 	key	  = "Label_QuickHotKey1",
			 	jump  =	48,
			},
	[41] = {
				name = _t"隐藏1",
				button = "CHECK_Quick3",
				label = "Label_Quick3",
			 	key	  = "Label_QuickHotKey3",
			 	jump	=	45,
			 	check_func = function() return GameApi.IsHidePlayer() end
			},
	[42] = {
				name = _t"隐藏2",
				button = "CHECK_Quick4",
				label = "Label_Quick4",
			 	key	  = "Label_QuickHotKey4",
			 	jump	=	46,
			 	check_func = function() return GameApi.IsHidePet() end
			},
	[43] = {
				name = "AFK",
				button = "Button_AFK",
				label = "Label_AFK",
			 	key	  = "Label_AFKHotKey",
			 	jump	=	47,
			},
	[44] = {
				name = _t"竞技",
				button = "Button_Fight",
				label = "Label_Fight",
			 	key	  = "Label_FightHotKeyBG",
			 	jump	=	58,
			},
	[45] = {
				name = _t"宝库",
				button = "Button_QuestRmb",
				label = "Label_QuestRmb",
			 	key	  = "Label_QuestRmbHotKeyBG",
			 	jump	=	55,
			},
	[46] = {
				name = _t"十二宫",
				button = "Button_Athena",
				label = "Label_Athena",
	 			key	  = "Label_AthenaHotKeyBG",
	 			jump	=	65,
			},
	[47] = {
				name = _t"电台",
				button = "Button_Radio",
				label = "Label_Radio",
	 			key	  = "Label_RadioHotKeyBG",
	 			jump	=	66,
			},
	[48] = {
				name = _t"雅典娜",
				button = "Button_AthenaSure",
				label = "Label_AthenaSure",
	 			key	  = "Label_AthenaSureHotKeyBG",
	 			jump	=	69,
			},
	[49] = {
				name  = _t"星币",
				button= "Button_Startrans",
				label = "Label_Startrans",
	 			key	  = "Label_StartransHotKeyBG",
	 			jump  =	70,
			},
	[50] = {
				name = _t"观星",
				button = "Button_StarSky",
				label = "Label_StarSky",
	 			key	  = "Label_StarSkyHotKeyBG",
	 			jump = 71,
			},
	[51] = {
				name = _t"师徒",
				button = "Button_Teacher",
				label = "Label_Teacher",
	 			key	  = "Label_TeacherHotKeyBG",
	 			jump = 72,

			},
	[52] = {
				name = _t"隐藏3",
				button = "Button_HideEffect",
				label = "Label_HideEffect",
			 	key	  = "Label_HideEffectHotKey",
			 	jump	=	73,
			},
	[54] = {
				name = _t"神器",
				button = "Button_Artifact",
				label = "Label_Artifact",
	 			key	  = "Label_ArtifactHotKeyBG",
	 			jump = 74,
			},
	[55] = {
				name = _t"物品锁",
				button = "Button_ItemLock",
				label = "Label_ItemLock",
	 			key	  = "Label_ItemLockHotKeyBG",
	 			jump = 82,
			},
	[56] = {
				name = _t"战队",
				button = "Button_FightGroup",
				label = "Label_FightGroup",
			 	key	  = "Label_FightGroupHotKeyBG",
			 	jump	=	86,
			},
	[57] = {
				name = _t"灵魂",
				button = "Button_SoulArmor",
				label = "Label_SoulArmor",
			 	key	  = "Label_SoulArmorHotKeyBG",
			 	jump	=	87,
			},
}
