--[[ @i18n quest ]]
local _t = require("i18n").context("quest")

QuestCategoryAliases =
{
	------ 主线任务 ----------
	main = _t"主线任务",
	book1 = _t"黄金十二宫篇",
	book2 = _t"海皇征战篇",
	book3 = _t"冥界讨伐篇",
	book4 = _t"冥界地狱篇",
	chapter1 = _t"第一卷 启程！圣斗士的传说！",
	chapter2 = _t"第二卷 守护！爱与正义的圣斗士！",
	chapter3 = _t"第三卷 激斗！银河下的战士！",
	chapter4 = _t"第四卷 出发！命运的少年！",
	chapter5 = _t"第五卷 追寻！知道真相的男人！",
	chapter6 = _t"第六卷 传承！千年不变的信念！",
	chapter7 = _t"第七卷 背叛！射手座黄金圣斗士！",
	chapter8 = _t"第八卷 苏醒！君临七海的血脉！",
	chapter9 = _t"第九卷 复苏！称霸世界的野心！",
	chapter10 = _t"第十卷 爆发！皇后岛的烈焰！",
	chapter11 = _t"终卷 黄金十二宫",
	chapter12 = _t"第一卷 封印！海皇之力量！",
	chapter13 = _t"第二卷 血与火！极北之地的荣耀！",
	chapter14 = _t"第三卷 大海啸！波塞冬的怒火！",
	chapter15 = _t"第四卷 死斗！蔚蓝的海底神殿！",
	chapter16 = _t"第一卷 挽歌！黄金毁灭者！",
	chapter17 = _t"第二卷 地狱之门！大圣战的序幕！",
	chapter18 = _t"第三卷 恸哭！背叛的黄金圣斗士！",
	chapter19 = _t"第四卷 上吧！通往冥界之门！",
	chapter20 = _t"第一卷 绝不回头！地狱中的阳光！",
	chapter21 = _t"第二卷 集结！黄金圣斗士！",
	chapter22 = _t"第三卷 极乐净土上",
	chapter23 = _t"第四卷 极乐净土下",
	book1juben = _t"剧情副本",
	book2juben = _t"剧情副本",
	book3juben = _t"剧情副本",


	------支线任务------------
	branch = _t"支线任务",
	tianma = _t"天马",
	bainiao = _t"白鸟",
	tianlong = _t"天龙",
	xiannv = _t"仙女",
	fenghuang = _t"凤凰",
	map_shengyu = _t"圣域",
	map_fushishan = _t"银河竞技场",
	map_lushan = _t"庐山",
	map_yiwangzhilu = _t"遗忘之路",
	map_huanghoudao = _t"死亡皇后岛",
	map_xiboliya = _t"东西伯利亚",
	map_yatelandisi = _t"亚特兰蒂斯",
	map_xiannvdao = _t"仙女岛",
	map_hadisi = _t"哈迪斯城",
	map_jilejingtu = _t"极乐净土",
	map_mingjiediyu = _t"冥界地狱",
	tiaozhan = _t"挑战任务",
	zhentan = _t"侦探任务",
	qiyu = _t"奇遇任务",
	huodong = _t"活动任务",
	ringtask = _t"女神的圣斗士（历练）",
	storage = _t"命运的试炼（历练）",
	soloku = _t"圣斗士之路（历练）",
	star = _t"星辰的史诗（挑战）",
	queen = _t"女神宝库",
	shengyi = _t"圣衣任务",
	cosmo = _t"小宇宙",
	chongwu = _t"守护星",
	mingjieruqin = _t"冥界入侵",
	zhiyin = _t"指引任务",
	title = _t"称号",
	shengzhan = _t"圣战回忆",
	shifengxue = _t"十风穴",
	sheshoutaowang = _t"射手的逃亡",
	gold12 = _t"黄金十二宫",
	icetemple = _t"冰海神殿",
	seven = _t"七大洋巨柱",
	dark12 = _t"冥界十二宫",
	bluecastle = _t"蓝冰堡",
	title = _t"称号任务",
	zhiyin = _t"指引任务",
	jixian = _t"极限任务",
	jieri = _t"节日任务",
	galaxy = _t"银河争霸",
	constellationup = _t"星座升华",
	mwzn = _t"冥王之怒",
}

local function TreeNode(alias, children)
	return {alias = alias, children = children}
end

QuestCategoryTree =
{
	------ 主线任务 ----------
	TreeNode("main", {
    	TreeNode("book1", {
			TreeNode("chapter1"),
			TreeNode("chapter2"),
			TreeNode("chapter3"),
			TreeNode("chapter4"),
			TreeNode("chapter5"),
			TreeNode("chapter6"),
			TreeNode("chapter7"),
			TreeNode("chapter8"),
			TreeNode("chapter9"),
			TreeNode("chapter10"),
			TreeNode("chapter11"),
			TreeNode("book1juben"),
		}),
		TreeNode("book2", {
			TreeNode("chapter12"),
			TreeNode("chapter13"),
			TreeNode("chapter14"),
			TreeNode("chapter15"),
			TreeNode("book2juben"),
		}),
		TreeNode("book3", {
			TreeNode("chapter16"),
			TreeNode("chapter17"),
			TreeNode("chapter18"),
			TreeNode("chapter19"),
			TreeNode("book3juben"),
		}),
		TreeNode("book4", {
			TreeNode("chapter20"),
			TreeNode("chapter21"),
			TreeNode("chapter22"),
			TreeNode("chapter23"),
		}),
    }),

	------ 支线任务 ----------
	TreeNode("branch", {
		    TreeNode("tianma"),
			TreeNode("bainiao"),
			TreeNode("tianlong"),
			TreeNode("xiannv"),
			TreeNode("fenghuang"),
			TreeNode("map_shengyu"),
			TreeNode("map_fushishan"),
			TreeNode("map_lushan"),
			TreeNode("map_yiwangzhilu"),
			TreeNode("map_huanghoudao"),
			TreeNode("map_xiboliya"),
			TreeNode("map_yatelandisi"),
			TreeNode("map_xiannvdao"),
			TreeNode("map_hadisi"),
			TreeNode("map_jilejingtu"),
			TreeNode("map_mingjiediyu"),
			TreeNode("tiaozhan"),
			TreeNode("zhentan"),
			TreeNode("qiyu"),
			TreeNode("huodong"),
			TreeNode("ringtask"),
			TreeNode("storage"),
			TreeNode("soloku"),
			TreeNode("star"),
			TreeNode("queen"),
			TreeNode("shengyi"),
			TreeNode("cosmo"),
			TreeNode("chongwu"),
			TreeNode("mingjieruqin"),
			TreeNode("shengzhan"),
			TreeNode("shifengxue"),
			TreeNode("sheshoutaowang"),
			TreeNode("gold12"),
			TreeNode("icetemple"),
			TreeNode("seven"),
			TreeNode("dark12"),
			TreeNode("bluecastle"),
			TreeNode("title"),
			TreeNode("zhiyin"),
			TreeNode("jixian"),
			TreeNode("jieri"),
			TreeNode("galaxy"),
			TreeNode("constellationup"),
			TreeNode("mwzn"),
    }),
}

QuestCategoryIcon =
{
	main = "res/quest/主线.tga",
	branch = "res/quest/支线.tga",
	book1juben = "res/quest/剧本.tga",
	book2juben = "res/quest/剧本.tga",
	book3juben = "res/quest/剧本.tga",
	tianma = "res/quest/天马.tga",
	bainiao = "res/quest/白鸟.tga",
	tianlong = "res/quest/天龙.tga",
	xiannv = "res/quest/仙女.tga",
	fenghuang = "res/quest/凤凰.tga",
	tiaozhan = "res/quest/挑战.tga",
	zhentan = "res/quest/侦探.tga",
	qiyu = "res/quest/奇遇.tga",
	huodong = "res/quest/活动.tga",
	ringtask = "res/quest/历练.tga",
	storage = "res/quest/历练.tga",
	soloku = "res/quest/历练.tga",
	queen = "res/quest/宝库.tga",
	star = "res/quest/挑战.tga",
	jixian = "res/quest/极限.tga",
	jieri = "res/quest/节日.tga",
}
