---------------------------------------------------------------
--  created:   2009.5.6
--  author:    liudong
--
--  各种常量以及通用资源。
---------------------------------------------------------------


CONSTANT_TABLE =
{
	fov = 56,
	spec_char_wid = 13,
}



UIMAN_NONE		= -1	-- 	None UI manager
UIMAN_LOGIN  	= 0		--	Login UI manager
UIMAN_INGAME 	= 1		--	In game UI manager
UIMAN_LOADING	= 2		--  Loading UI manager



-- gender
GENDER_MALE   = 0
GENDER_FEMALE = 1
GENDER_BOTH	  = 2

-- lve
USE_EXP2_LEV = 100

-- task types
TASK_BRANCH  = 0
TASK_KEY     = 1
TASK_HIDDEN  = 2
TASK_STORAGE = 3

-- birth area
RACE_IOS			= 1		--希腊伊奥斯岛
RACE_LUSHAN			= 2		--中国庐山 
RACE_SIBERIA		= 3		--东西伯利亚
RACE_ANDROMEDA		= 4		--安多罗美达（仙女岛）
RACE_DEATHQUEEN		= 5		--死亡皇后岛

-- prof type
PROF_RESERVE		= 0 	--保留
PROF_DEFAULT		= 1 	--默认
PROF_PEGASI			= 2 	--天马,星矢
PROF_CYGNI			= 3 	--白鸟,冰河
PROF_DRACONIS	    = 4 	--天龙,紫龙
PROF_ANDROMEDAE		= 5		--仙女,瞬
PROF_PHOENIX		= 6		--凤凰,一辉
PROF_GEMINORUM		= 7		--双子,加隆
PROF_JUDGE			= 8		--圣斗士·裁
PROF_MILITARY		= 9		--圣斗士·武
PROF_NUM			= 10

-- 升阶
PROF_UP_MASK		=	100
PROF_SAGITTARIUS	= PROF_PEGASI + PROF_UP_MASK --射手,天马升阶
PROF_AQUARIUS		= PROF_CYGNI + PROF_UP_MASK 	--水瓶，白鸟升阶
PROF_LIBRA	    	= PROF_DRACONIS + PROF_UP_MASK 	-- 天秤，天龙升阶
PROF_VIRGO			= PROF_ANDROMEDAE + PROF_UP_MASK	-- 处女，仙女升阶
PROF_LEO			= PROF_PHOENIX + PROF_UP_MASK	--狮子,凤凰升阶
PROF_GEMINI			= PROF_GEMINORUM + PROF_UP_MASK	--双子，海龙升阶

-- weapon type
WEAPON_NONE			= 0
WEAPON_TYPE1		= 1
WEAPON_TYPE2		= 2
WEAPON_TYPE3		= 3
WEAPON_TYPE4		= 4
WEAPON_TYPE5		= 5
WEAPON_TYPE6		= 6
WEAPON_TYPE7		= 7
WEAPON_TYPE8		= 8

-- move env type
MOVEENV_GROUND 		= 0		--	Move on ground
MOVEENV_WATER 		= 1
MOVEENV_AIR			= 2


-- window message
WM_KEYDOWN               = 0x0100
WM_KEYUP                 = 0x0101
WM_CHAR                  = 0x0102
WM_MOUSEMOVE             = 0x0200
WM_LBUTTONDOWN           = 0x0201
WM_LBUTTONUP             = 0x0202
WM_LBUTTONDBLCLK         = 0x0203
WM_RBUTTONDOWN           = 0x0204
WM_RBUTTONUP             = 0x0205
WM_RBUTTONDBLCLK         = 0x0206
WM_MBUTTONDOWN           = 0x0207
WM_MBUTTONUP             = 0x0208
WM_MBUTTONDBLCLK         = 0x0209
WM_MOUSEWHEEL            = 0x020A
WM_IME_SETCONTEXT        = 0x0281
WM_IME_NOTIFY            = 0x0282
WM_IME_CONTROL           = 0x0283
WM_IME_COMPOSITIONFULL   = 0x0284
WM_IME_SELECT            = 0x0285
WM_IME_CHAR              = 0x0286
WM_IME_REQUEST           = 0x0288
WM_IME_KEYDOWN           = 0x0290
WM_IME_KEYUP             = 0x0291
WM_IME_STARTCOMPOSITION  = 0x010D
WM_IME_ENDCOMPOSITION    = 0x010E
WM_IME_COMPOSITION       = 0x010F
WM_IME_KEYLAST           = 0x010F

--v key
VK_TAB          =  0x09
VK_ENTER 		=  0x0D
VK_SHIFT		=  0x10
VK_CONTROL      =  0x11
VK_ALT          =  0x12
VK_ESCAPE       =  0x1B
VK_SPACE        =  0x20
VK_PRIOR 		=  0x21
VK_NEXT 		=  0x22
VK_LEFT			=  0x25
VK_UP			=  0x26
VK_RIGHT		=  0x27
VK_DOWN			=  0x28
VK_DELETE       =  0x2E
VK_OEM_3        =  0xC0   -- '`~' for US
VK_F1           =  0x70
VK_F2           =  0x71
VK_F3           =  0x72
VK_F4           =  0x73
VK_F5           =  0x74
VK_F6           =  0x75
VK_F7           =  0x76
VK_F8           =  0x77
VK_F9           =  0x78
VK_F10          =  0x79
VK_F11          =  0x7A
VK_F12          =  0x7B


VK_A            =  65
VK_B            =  66
VK_C            =  67
VK_D            =  68
VK_E            =  69
VK_F            =  70
VK_G            =  71
VK_H            =  72
VK_I            =  73
VK_J            =  74
VK_K            =  75
VK_L            =  76
VK_M            =  77
VK_N            =  78
VK_O            =  79
VK_P            =  80
VK_Q            =  81
VK_R            =  82
VK_S            =  83
VK_T            =  84
VK_U            =  85
VK_V            =  86
VK_W            =  87
VK_X            =  88
VK_Y            =  89 
VK_Z            =  90

--主键盘数字键
VK_0            =  48
VK_1            =  49
VK_2            =  50
VK_3            =  51
VK_4            =  52
VK_5            =  53
VK_6            =  54
VK_7            =  55
VK_8            =  56
VK_9            =  57



-- message box type
MB_OK			= 0
MB_OKCANCEL		= 1
MB_YESNO		= 4

-- message box command id
IDOK		  = 1
IDCANCEL	  = 2
IDYES         = 6
IDNO          = 7


-- Aui object
AUISTILLIMAGEBUTTON_STATE_NORMAL  = 0
AUISTILLIMAGEBUTTON_STATE_CLICK	  = 2

AUIDIALOG_ALIGN_NONE		=	0
AUIDIALOG_ALIGN_INSIDE		=	1
AUIDIALOG_ALIGN_OUTSIDE		=	2
AUIDIALOG_ALIGN_LEFT		=	3
AUIDIALOG_ALIGN_RIGHT		=	4
AUIDIALOG_ALIGN_TOP			=	5
AUIDIALOG_ALIGN_BOTTOM		=	6
AUIDIALOG_ALIGN_CENTER		=	7


-- 图标类型
ICONS_ACTION 	=	0
ICONS_SKILL 	= 	1 
ICONS_STATE		= 	2
ICONS_SKILLGRP	=	3
ICONS_GUILD		=	4
ICONS_PET		=	5
ICONS_LOTTERY	=	6
ICONS_NPC		=	7
ICONS_COVER		=	8
ICONS_HINT		=	9
ICONS_MARK		=	10
ICONS_MAX		=	11
ICONS_INVENTORY	=	12
ICONS_ALL_MAX	=	13


--物品自定义颜色, 限制6位
COLOR_WHITE						= 0xffffff 	--  白
COLOR_PURPLE					= 0xfd7fff	--  粉
COLOR_ORANGE					= 0xF27900 	--  橙
COLOR_BLUE						= 0x8080ff 	--  天蓝
COLOR_GREEN						= 0x6CFB4B 	--  绿
COLOR_RED						= 0xff0000 	--  红
COLOR_DARKGOLD					= 0xff6000 	--  暗金
COLOR_GRAY						= 0x909090 	--  灰
COLOR_YELLOW					= 0xfcff00 	--  亮黄
COLOR_CYANINE					= 0x80ffff 	--  青

--物品品质颜色, 限制6位
QUALITY_COLOR_0					= 0x787878 	--  残破[灰]
QUALITY_COLOR_1					= 0xffffff 	--  普通[白]
QUALITY_COLOR_2					= 0x00cc33 	--  优秀[绿]
QUALITY_COLOR_3					= 0x0099ff	--  精良[蓝]
QUALITY_COLOR_4					= 0xcc33ff 	--  史诗[紫]
QUALITY_COLOR_5					= 0xff6600 	--  传说[橙]
QUALITY_COLOR_6					= 0xffff33 	--  预留[金]
QUALITY_COLOR_7					= 0xff00ff 	--  预留[粉]
QUALITY_COLOR_8					= 0xffd700 	--  套装
QUALITY_COLOR_9					= 0xad8300 	--  高级套装


--BUFF类型
SKILL_BUFF_TYPE_INVALID 				= -1
SKILL_BUFF_TYPE_BUFF					= 0
SKILL_BUFF_TYPE_DEBUFF					= 1
SKILL_BUFF_TYPE_NONE					= 2
SKILL_BUFF_TYPE_BUFF_NOT_SHOW_TIME		= 3
SKILL_BUFF_TYPE_DEBUFF_NOT_SHOW_TIME	= 4
SKILL_BUFF_TYPE_SPECIAL					= 5
SKILL_BUFF_TYPE_PSEUDO_BUFF_EXP			= 6
SKILL_BUFF_TYPE_NUM						= 7


TYPE_ATTACK				= 1		-- 主动攻击
TYPE_BLESS				= 2		-- 主动祝福
TYPE_CURSE				= 3		-- 主动诅咒
TYPE_PASSIVE			= 4		-- 被动技能
TYPE_ENABLED			= 5		-- 辅助技能
TYPE_SYNTHESIZE			= 6		-- 合成技能


FREQUENCY_FIRST			= 1		-- 第一次
FREQUENCY_LEVUP			= 2		-- 升级
FREQUENCY_LOGIN			= 3		-- 登录
FREQUENCY_TIME			= 4		-- 时间


SELF_LEVEL_GROWTH			= 1		--等级成长
SELF_XINFA_SKILL			= 2		--心法技能
SELF_TEXUN_SKILL			= 3		--特训技能
SELF_CHUILIAN_SKILL			= 4		--锤炼技能
--小宇宙
MICROCOSM_JINGJIE_GROWTH	= 5		--境界成长
MICROCOSM_JIDU_XINHUN		= 6		--计都星魂
MICROCOSM_LUOHOU_XINHUN		= 7		--罗睺星魂
MICROCOSM_ZHENYANG_XINHUN	= 8		--真央星魂
--圣衣
SAINTCLOTHES_BRONZE			= 9		--青铜圣衣
SAINTCLOTHES_SILVER			= 10	--白银圣衣
SAINTCLOTHES_GOLDEN			= 11	--黄金圣衣
SAINTCLOTHES_DEITY			= 12	--神圣衣
SAINTCLOTHES_SURPLICE		= 13	--冥衣
SAINTCLOTHES_SCALE			= 14 	--鳞衣
--装备
EQUIPMENT_QUALITY			= 15	--品质成长
EQUIPMENT_STRENGTHEN		= 16	--强化成长
EQUIPMENT_DEVIL				= 17	--附魔成长
EQUIPMENT_SUIT				= 18	--连锁成长
--宝物
TREASURE_QUALITY			= 19	--品质成长	--枚举值保持与装备一致
TREASURE_STRENGTHEN			= 20	--强化成长
TREASURE_DEVIL				= 21	--附魔成长
--侍从
ATTENDANT_APTITUDE			= 22	--资质成长
ATTENDANT_COMBAT			= 23	--战队成长
ATTENDANT_OTHER				= 24	--其他
--收藏
COLLECTION_GOODS			= 25	--收藏品
COLLECTION_TITLE			= 26	--称号
COLLECTION_ACHIEVEMENT		= 27	--成就
--星座神话
CONSTELLATION_DISCOVERY		= 28    --星域探索
CONSTELLATION_ARTIFACT		= 29	--神器
CONSTELLATION_ARMOR			= 30	--灵魂之甲




--help_secretary界面显示四角的箭头
LEFT_TOP_CORNER 	= 1		
RIGHT_TOP_CORNER 	= 2
LEFT_BOTTOM_CORNER 	= 3
RIGHT_BOTTOM_CORNER = 4

-- help dynamic direction 引起下一步的动作
DYNAMIC_DIR_MSG_CLICK = 1
DYNAMIC_DIR_MSG_ONHOVER = 2


PANEL_SHOW_TIME = 5000 --分步帮助界面显示下一步的默认间隔时间



-- data types in element data
local _DATA_TYPE = 
{
	"DT_INVALID",
	"DT_EQUIPMENT_ADDON",
	"DT_EQUIPMENT_ESSENCE",
	"DT_REFINE_TICKET_ESSENCE",
	"DT_MEDICINE_ESSENCE",
	"DT_MATERIAL_ESSENCE",
	"DT_SKILLTOME_ESSENCE",
	"DT_TRANSMITROLL_ESSENCE",
	"DT_LUCKYROLL_ESSENCE",
	"DT_TOWNSCROLL_ESSENCE",
	"DT_REVIVESCROLL_ESSENCE",
	"DT_TASKMATTER_ESSENCE",
	"DT_DROPTABLE_ESSENCE",
	"DT_MONSTER_ESSENCE",
	"DT_NPC_TALK_SERVICE",
	"DT_NPC_SELL_SERVICE",
	"DT_NPC_BUY_SERVICE",
	"DT_NPC_TASK_IN_SERVICE",
	"DT_NPC_TASK_OUT_SERVICE",
	"DT_NPC_TASK_MATTER_SERVICE",
	"DT_NPC_HEAL_SERVICE",
	"DT_NPC_TRANSMIT_SERVICE",
	"DT_NPC_PROXY_SERVICE",
	"DT_NPC_STORAGE_SERVICE",
	"DT_NPC_TYPE",
	"DT_NPC_ESSENCE",
	"DT_TALK_PROC",
	"DT_RECIPE_ESSENCE",
	"DT_ENEMY_FACTION_CONFIG",
	"DT_CHARRACTER_CLASS_CONFIG",
	"DT_PARAM_ADJUST_CONFIG",
	"DT_TASKDICE_ESSENCE",
	"DT_TASKNORMALMATTER_ESSENCE",
	"DT_PLAYER_LEVELEXP_CONFIG",
	"DT_MINE_ESSENCE",
	"DT_FIREWORKS_ESSENCE",
	"DT_NPC_WAR_TOWERBUILD_SERVICE",
	"DT_PLAYER_SECONDLEVEL_CONFIG",
	"DT_NPC_RESETPROP_SERVICE",
	"DT_ESTONE_ESSENCE",
	"DT_PSTONE_ESSENCE",
	"DT_SSTONE_ESSENCE",
	"DT_RECIPEROLL_ESSENCE",
	"DT_SUITE_ESSENCE",
	"DT_DOUBLE_EXP_ESSENCE",
	"DT_NPC_EQUIPBIND_SERVICE",
	"DT_NPC_EQUIPDESTROY_SERVICE",
	"DT_NPC_EQUIPUNDESTROY_SERVICE",
	"DT_SKILLMATTER_ESSENCE",
	"DT_VEHICLE_ESSENCE",
	"DT_COUPLE_JUMPTO_ESSENCE",
	"DT_LOTTERY_ESSENCE",
	"DT_CAMRECORDER_ESSENCE",
	"DT_TITLE_PROP_CONFIG",
	"DT_SPECIAL_ID_CONFIG",
	"DT_TEXT_FIREWORKS_ESSENCE",
	"DT_TALISMAN_MAINPART_ESSENCE",
	"DT_TALISMAN_EXPFOOD_ESSENCE",
	"DT_TALISMAN_MERGEKATALYST_ESSENCE",
	"DT_TALISMAN_ENERGYFOOD_ESSENCE",
	"DT_SPEAKER_ESSENCE",
	"DT_PLAYER_TALENT_CONFIG",
	"DT_POTENTIAL_TOME_ESSENCE",
	"DT_AIRCRAFT_ESSENCE",
	"DT_CHANGE_SHAPE_ESSENCE",
	"DT_SUMMON_MONSTER_ESSENCE",
	"DT_PET_BEDGE_ESSENCE",
	"DT_PET_FOOD_ESSENCE",
	"DT_PET_SKILL_ESSENCE",
	"DT_PET_ARMOR_ESSENCE",
	"DT_MERGE_RECIPE_ESSENCE",
	"DT_NPC_HOTEL_SERVICE",
	"DT_STATUS_POINT_PROP_CONFIG",
	"DT_PLAYER_STATUS_POINT_CONFIG",
	"DT_PRODUCE_TYPE_CONFIG",
	"DT_NPC_LEARN_PRODUCE_SERVICE",
	"DT_AI_HELPER_ESSENCE",
	"DT_ITEM_TRADE_CONFIG",
	"DT_LEVELUP_MODIFY_CONFIG",
	"DT_SKILL_LEARN_CONFIG",
	"DT_EQUIPMENT_QUALITY_CONFIG",
	"DT_EQUIPMENT_ENHANCE_TRANSFORM_CONFIG",
	"DT_TRADE_DISTANCE_CONFIG",
	"DT_NPC_LEARN_SKILL_SERVICE",
	"DT_NPC_TRADE_PORT_SERVICE",
	"DT_NPC_SWITCH_PROF_SERVICE",
	"DT_TRADE_ITEM_ESSENCE",
	"DT_ADDON_PACKAGE_CONFIG",
	"DT_ADDON_STORAGE_CONFIG",
	"DT_EQUIPMENT_PROPERTY_RANDOM_CONFIG",
	"DT_INSTANCE_CONFIG",
	"DT_BOOK_ESSENCE",
	"DT_TRADE_RANDOM_EVENT_CONFIG",
	"DT_MONEYBAG_ESSENCE",
	"DT_SYSTEM_MAIL_CONFIG",
	"DT_INSTANCE_TABLE_CONFIG",
	"DT_PET_REVIVE_ESSENCE",
	"DT_FIRE_ESSENCE",
	"DT_KM_PARAM_ADJUST_CONFIG",
	"DT_TIME_GIFT_BAG_CONFIG",
	"DT_EQUIPMENT_ENHANCE_MODEL_CONFIG",
	"DT_IDENTIFY_SCROLL_ESSENCE",
	"DT_CHAR_CAMERA_CONFIG",
	"DT_DYNAMIC_INSTANCE_CONFIG",
	"DT_DYNAMIC_MONSTER_PACK_ESSENCE",
	"DT_PLAYER_SUB_PROF_LEVEL_EXP_CONFIG",
	"DT_PET_EGG_ESSENCE",
	"DT_SPECIAL_STATUS_PACKAGE_CONFIG",
	"DT_STATUS_PACKAGE_EXPRESSIONS_CONFIG",
	"DT_RESURRECT_TIME_CONFIG",
	"DT_NPC_RECIPE_ESSENCE",
	"DT_GIFT_BAG_CONFIG",
	"DT_SPECIAL_ITEMS_PACK_ESSENCE",
	"DT_TRANSMITBOX_ESSENCE",
	"DT_REPUTATION_CONFIG",
	"DT_TASK_FIX_CONFIG",
	"DT_BODY_TRANSFORM_CONFIG",
	"DT_MONSTER_NPC_PACK_CONFIG",
	"DT_TEXT_PACK_CONFIG",
	"DT_STAR_SOUL_CHAIN_CONFIG",
	"DT_STAR_SOUL_STONE_ESSENCE",
	"DT_STAR_SOUL_CHAIN_COMBO_CONFIG",
	"DT_COMBO_PACK_CONFIG",
	"DT_MINE_PACK_CONFIG",
	"DT_SUMMON_MONSTER_NPC_PACK_CONFIG",
	"DT_SUMMON_MINE_PACK_CONFIG",
	"DT_ENHANCE_ITEM_ESSENCE",
	"DT_ENHANCE_SHOW_CONFIG",
	"DT_WORLD_TELEPORT_POINT_CONFIG",
	"DT_ENHANCE_TRANSFER_CONFIG",
	"DT_STAR_SOUL_STONE_UPGRADE_ITEM_ESSENCE",
	"DT_EQUIPMENT_PROCESSING_ITEM_ESSENCE",
	"DT_PET_APTITUDE_STONE_ESSENCE",
	"DT_PET_SKILL_LEVEL_UP_STONE_ESSENCE",
	"DT_COMMON_MONSTER_CONFIG",
	"DT_PET_GROWTH_STONE_ESSENCE",
	"DT_PET_CATCHER_ESSENCE",
	"DT_SUMMON_CATEGORY_CONFIG",
	"DT_STORED_EXP_CONFIG",
	"DT_PASSIVE_SKILL_CONFIG",
	"DT_DROP_BY_LEVEL_CONFIG",
	"DT_STORAGE_TASK_MAX_COUNT_CONFIG",
	"DT_LEVEL_ADAPT_WEIGHT_CONFIG",
	"DT_GUARDIAN_STAR_CONFIG",
	"DT_GUARDIAN_STONE_ESSENCE",
	"DT_LEAGUE_WAR_CONFIG",
	"DT_GUARDIAN_SOUL_ESSENCE",
	"DT_GUARDIAN_SOUL_SKILL_ESSENCE",
	"DT_GUARDIAN_SOUL_SKILL_UP_ESSENCE",
	"DT_GUARDIAN_SOUL_APTITUDE_STONE_ESSENCE",
	"DT_REST_EXP_CONFIG",
	"DT_NPC_DUNGEON_SERVICE",
	"DT_ENFORCED_MOVE_CONFIG",
	"DT_PROF_SELECT_SERVICE",
	"DT_STAR_BOARD_CONFIG",
	"DT_STAR_CONFIG",
	"DT_ASTROLOGY_CONFIG",
	"DT_STAR_SOUL_ESSENCE",
	"DT_ASTROLOGY_ITEM_ESSENCE",
	"DT_EXTEND_ENHANCE_LIMIT_ITEM_ESSENCE",
	"DT_SOLO_CHALLENGE_DUNGEON_CONFIG",
	"DT_CLOTH_CONFIG",
	"DT_QTE_CONFIG",
	"DT_ATHENA_BLESSING_CONFIG",
	"DT_SELF_SERVICE_CONFIG",
	"DT_CLOTH_UPGRADE_ITEM_ESSENCE",
	"DT_ATHENA_AWARD_CONFIG",
	"DT_DAILY_LIMITATION_CONFIG",
	"DT_HOOK_MODEL_CONFIG",
	"DT_NPC_LIMITED_SALE_SERVICE",
	"DT_CLOTH_UPGRADE_CONFIG",
	"DT_PRODUCE_ENERGY_CONFIG",
	"DT_SUIT_TAG_CONFIG",
	"DT_SUIT_TAG_ACTIVE_CONFIG",
	"DT_VALUE_INCREASE_ESSENCE",
	"DT_PET_CONFIG",
	"DT_PET_ACCESSORY_ESSENCE",
	"DT_PRAY_EXP_CONFIG",
	"DT_CONSTELLATION_GUARD_CONFIG",
	"DT_LEAGUE_REPU_CONFIG",
	"DT_ALBUM_CONFIG",
	"DT_MODEL_CANDIDATE_CONFIG",
	"DT_COMBAT_PET_ESSENCE",
	"DT_COMBAT_PET_SKILL_BOOK_ESSENCE",
	"DT_COMBAT_PET_EQUIPMENT_ESSENCE",
	"DT_STAR_SOUL_BOX_ESSENCE",
	"DT_EQUIPMENT_APPEARANCE_ESSENCE",
	"DT_PLAYER_APPEARANCE_ESSENCE",
	"DT_DRIFT_BOTTLE_ESSENCE",
	"DT_COMBAT_PET_CONFIG",
	"DT_VIP_CONFIG",
	"DT_MONSTER_AFFIX_COMBINATION_CONFIG",
	"DT_MONSTER_AFFIX_RANDOM_PACK_CONFIG",
	"DT_QTE_PLAYER_MONSTER_INTERACTION_CONFIG",
	"DT_BATTLE_FIELD_CONFIG",
	"DT_TEAM_POWER_UP_CONFIG",
	"DT_DIVINING_ITEM_ESSENCE",
	"DT_WING_CONFIG",
	"DT_SOLO_ARENA_CONFIG",
	"DT_LUCKY_DRAW_CONFIG",
	"DT_NPC_BATTLE_FIELD_SERVICE",
	"DT_EQUIPMENT_ENHANCE_COMBO_CONFIG",
	"DT_NPC_IMPRINT_SERVICE",	
	"DT_MONSTER_KILL_LIMIT_CONFIG",
	"DT_ITEM_EXCHANGE_CONFIG",
	"DT_NPC_ITEM_EXCHANGE_SERVICE",
	"DT_EMOTION_ICON_PACK_ESSENCE",
	"DT_DAILY_BENEFIT_TASK_CONFIG",
	"DT_REVENGE_ITEM_ESSENCE",
	"DT_STAR_FIELD_EXPLORE_CONFIG",
	"DT_ATOM_GENERATION_CONFIG",
	"DT_ATOM_COMBINE_CONFIG",
	"DT_ATOM_CHAIN_CONFIG",
	"DT_ATOM_REQUIREMENT_CONFIG",
	"DT_COSMOS_STAR_FORCE_CONFIG",
	"DT_STAR_FIELD_INCUBATION_CONFIG",
	"DT_EQUIPMENT_DYE_ESSENCE",
	"DT_RELIC_ESSENCE",
	"DT_CLOAK_CONFIG",
	"DT_RELIC_CONFIG",
	"DT_RELIC_PROP_CONFIG",
	"DT_RELIC_COMBO_CONFIG",
	"DT_SUIT_TAG_MIGRATION_CONFIG",
	"DT_MARRIAGE_CERTIFICATE_ESSENCE",
	"DT_NPC_FORCE_SELECT_SERVICE",
}
DATA_TYPE = {}
for k,v in pairs(_DATA_TYPE) do
    DATA_TYPE[v] = k-1
end



--系统默认热键的响应id
LKEY_UI_CHAT_REPLY			= 11	--  聊天栏回复
LKEY_UI_SHOWDLG_CHARACTER	= 21	--	show dialog character
LKEY_UI_SHOWDLG_CASHSHOP	= 22	--	show dialog cash shop
LKEY_UI_SHOWDLG_INVENTORY	= 23	--	show dialog inventory
LKEY_UI_SHOWDLG_TASK		= 24	--	show dialog task
LKEY_UI_SHOWDLG_SKILL		= 25	--	show dialog skill
LKEY_UI_SHOWDLG_WORLDMAP	= 26	--	show dialog world map
LKEY_UI_SHOWDLG_KOSUMO		= 27	--	show dialog kosumo
LKEY_UI_SHOWDLG_SAINTCLOTH	= 28	--	show dialog cloth
LKEY_UI_SHOWDLG_FRIEND		= 29	--	show dialog produce
LKEY_UI_SHOWDLG_LEAGUE		= 30	--	show dialog league
LKEY_UI_SHOWDLG_RANKLIST	= 31	--	show dialog rank list		
LKEY_UI_SHOWDLG_SEQUENCE	= 32	--	show dialog sequence	
LKEY_UI_SHOWDLG_PRODUCE		= 33	--	show dialog produce
LKEY_UI_SHOWDLG_PET			= 34	--	show dialog pet
LKEY_UI_SHOWDLG_SYSTEM		= 35	--	show dialog system
LKEY_UI_SHOWDLG_DAILY		= 36	--	show dialog daily
LKEY_UI_SHOWDLG_GROUP		= 37	--	show dialog group team
LKEY_UI_SHOWDLG_CIRCLE		= 38	--	show dialog circle
LKEY_UI_SHOWDLG_MINIPET		= 39	--	show dialog mini pet
LKEY_UI_SHOWDLG_PHOTOBOOK	= 40	--	show dialog photo book
LKEY_UI_SHOWDLG_ACHI		= 41	--	show dialog achievement
LKEY_UI_SHOWDLG_REPUTE		= 42	--	show dialog repute
LKEY_UI_SHOWDLG_SOULSKILL	= 43    --  显示斗魂
LKEY_UI_SHOWDLG_CAMERA		= 44    --  显示照相机
LKEY_UI_SHOWDLG_QUEST		= 45    --  女神宝库
LKEY_UI_SHOWDLG_VIP			= 46    --  VIP
LKEY_UI_SHOWDLG_COURSE 		= 47 	--	进程
LKEY_UI_SHOWDLG_TEACHER		= 48 	--	show dialog teacher
LKEY_UI_SHOWDLG_STAREXPLORE = 49 	--	显示星域探索对话框
LKEY_UI_SHOWDLG_ARMOR		= 50 	--	显示灵魂之甲
LKEY_UI_SHOW_ALLPANELS		= 51 	--  显示所有界面

LKEY_HIDE_PETMODEL 			= 104	-- 隐藏宠物
LKEY_HIDE_MONSTERMODEL		= 105	-- 隐藏怪物
LKEY_HIDE_PLAYERMODEL		= 106 	-- 隐藏玩家
LKEY_HIDE_GFX				= 107 	-- 隐藏特效
LKEY_UI_CHAT_ENTER			= 108	-- 进入聊天
LKEY_UI_SHOWDLG_GMCONSOLE	= 117	-- 显示gm面板
LKEY_UI_SHOWDLG_CONSOLE		= 118	-- 显示控制台

HOST_WORK = {
	WORK_INVALID = -1
}
local _host_player_work =
{
	"WORK_STAND",
	"WORK_MOVETOPOS",
	"WORK_TRACEOBJECT",
	"WORK_HACKOBJECT",
	"WORK_SPELLOBJECT",
	"WORK_USEITEM",
	"WORK_DEAD",
	"WORK_FOLLOW",
	"WORK_AUTOMOVE",
	"WORK_FLYOFF",
	"WORK_FREEFALL",
	"WORK_SIT",
	"WORK_PICKUP",
	"WORK_CONCENTRATE",
	"WORK_REVIVE",
	"WORK_BEBOUND",
	"WORK_GENERAL_OPRT",
	"WORK_GATHER",
	"WORK_FIRE",
	"WORK_SKILL_PREPARE",
	"WORK_PRODUCE",
	"WORK_STUN",
	"WORK_DRIFT",
	"WORK_DOWN",
	"WORK_HOLDING",
	"WORK_THROWING",
	"WORK_NAVIGATE",
	"WORK_BE_HOOKED",
	"WORK_CLIMB",
	"WORK_INTERACTION",
}

for i, v in ipairs(_host_player_work) do
	HOST_WORK[v] = i - 1
end


-- 触发事件：界面操作动态指导 马远征
LEVT_UI_DYNAMIC_DIRECTION		=	10000

--lua event for notify
LEVT_TASK_ACCEPT				=   30000	-- 接取任务, 参数:任务id
LEVT_TASK_FINISH				=   30001	-- 完成任务, 参数:任务id
LEVT_SCENE_PARAMETERS			=	30002	-- 场景参数变化
LEVT_SPEC_PLOT_CRY				=	30003	-- 特殊策略喊话
LEVT_LEARN_SKILL				=	30004	-- 学习技能, 参数:技能id
LEVT_STRATEGY					=	30005	-- 头像喊话, 特殊策略喊话逻辑用
LEVT_NPC_TALK					=	30006	-- NPC交谈, 参数:NPC的id
LEVT_CONSTELLATION_DATA			=	30007	-- 星座运势变化
LEVT_OBTAIN_ITEM				=	30008	-- 获得物品, 参数:物品id
LEVT_LEAGUE_REPU_CHANGE			=	30009	-- 军团声望变化
LEVT_PROF_SWITCHED				=	30010	-- 职业变化
LEVT_CALL_PET					= 	30011	-- 召唤宠物
LEVT_PET_LEVUP					= 	30012	-- 宠物升级
LEVT_HOST_HP_LOW				= 	30013	-- 主角生命值低, 宠物喊话逻辑用
LEVT_PET_HP_LOW					= 	30014	-- 宠物生命值低, 宠物喊话逻辑用
LEVT_IN_FIGHT					= 	30015	-- 战斗状态, 宠物喊话逻辑用
LEVT_IN_LEISURE					= 	30016	-- 休闲状态, 宠物喊话逻辑用
LEVT_BEAN_UPDATE				=	30017	-- 天马攒豆数量变化
LEVT_HOST_REPU_CHANGE			=	30018	-- 个人声望改变	
LEVT_HOST_INC_REPU_CHANGE		=	30019	-- 个人增量声望改变
LEVT_OPEN_DIALOG				=	30020	-- 打开界面，参数 界面名	
LEVT_COMBAT_POWER_CHANGE		=	30021	-- 战斗力改变
LEVT_LEVEL_UP					=	30022	-- 玩家升级
LEVT_USE_ITEM					=	30023	-- 使用物品
LEVT_PACKAGE_FULL				=	30024	-- 包裹满
LEVT_REVIVE        				=	30025	--	复活
LEVT_CHOOSE_STYLE_FINISHED		=	30026	--	完成风格选择
LEVT_DRAG_LOCKING_SC			=	30027	--	拖动锁定的快捷栏
LEVT_GATHER_START				=	30028	-- 采矿开始	
LEVT_GATHER_SUCCESS				=	30029	-- 采矿成功	
LEVT_AUTO_ROUTE_TELEPORT		=	30030	-- 自动寻路传送开启
	
--lua event for help system
LEVT_FIRST_TASK_ACCEPT			=   40000	-- 第一次接取任务	 
LEVT_FIRST_TASK_FINISH			=	40001	-- 第一次完成任务
LEVT_FIRST_ACCEPT_ID_TASK		=	40002   -- 第一次接取特定id任务, 参数:任务id(需要在helpconfig.lua中配置)
LEVT_FIRST_FINISH_ID_TASK		=	40003	-- 第一次完成特定id任务, 参数:任务id(需要在helpconfig.lua中配置)
LEVT_FIRST_FIGHT				=   40004	-- 第一次进入战斗
LEVT_FIRST_GAIN_SPEC_ITEM		=	40005   -- 第一次获取特定id物品, 参数:物品id(需要在helpconfig.lua中配置)
LEVT_FIRST_USE_SPEC_ITEM		=	40006	-- 第一次使用特定id物品, 参数:物品id(需要在helpconfig.lua中配置)
LEVT_FIRST_EQUIP_SUCCESS		=	40007	-- 第一次装备
LEVT_FIRST_EQUIP_SPEC_TYPE		=	40008	-- 第一次装备特定id装备, 参数:装备id(需要在helpconfig.lua中配置)
LEVT_FIRST_CAST_SPEC_SKILL		=	40009	-- 第一次施放特定id技能, 参数:技能id(需要在helpconfig.lua中配置)
LEVT_FIRST_GAIN_EQUIPMENT		=	40010	-- 第一次获得装备
LEVT_FIRST_MONSTER_DRIFT		=	40011	-- 第一次怪物浮空, 好像已经不能用
LEVT_FIRST_SHOW_DIALOG			=	40012	-- 第一次显示某界面, 参数:界面名(需要在helpconfig.lua中配置)
LEVT_FIRST_REACH_LVL			=	40013	-- 第一次到达某个等级, 参数:达到等级
LEVT_FIRST_ENTER_GAME			=	40014	-- 第一次进入游戏
LEVT_FIRST_LOW_HP_IN_FIGHT		=	40015	-- 第一次在战斗中血量低
LEVT_FIRST_LEARN_SKILL			=	40016	-- 第一次学习技能
LEVT_FIRST_NPC_TALK				=	40017	-- 第一次和NPC交谈
LEVT_FIRST_LOW_HP_OUT_FIGHT		=	40018	-- 第一次在战斗外血量低 
LEVT_FIRST_MONSTER_POWER_EXHAUST=	40019	-- 第一次怪物力竭, 好像已经不能用
LEVT_FIRST_SELECT_PET_MONSTER	=   40020	-- 第一次选中宠物怪
LEVT_FIRST_EQUIP_PET			=	40021	-- 第一次装备宠物
LEVT_FIRST_CALL_PET				=	40022	-- 第一次召唤宠物
LEVT_FIRST_PET_LVL_UP			=	40023	-- 第一次宠物升级
LEVT_FIRST_PET_DIE				=	40024	-- 第一次宠物死亡
LEVT_FIRST_PET_CAN_UPGRADE		=	40025	-- 第一次宠物可以升级
LEVT_FIRST_PICKUP_ITEM			=	40026	-- 第一次拾取物品
LEVT_FIRST_TASK_AWARD_ITEM		=	40027	-- 第一次任务奖励获得物品
LEVT_FIRST_PURCHASE_ITEM		=	40028	-- 第一次从NPC购买物品

-- 成就条件完成事件
LEVT_ACHIEVE_CONDITION_BEGIN	=	40040		
LEVT_FIRST_DIE					=	40041	--		首次死亡
LEVT_FIRST_MARRY				=	40042	--		首次结婚
LEVT_FIRST_APPRENTICE			=	40043	--		首次拜师
LEVT_FIRST_SHOUTU				=	40044	--		首次收徒
LEVT_FIRST_INLEAGUE				=	40045	--		首次加入或创建军团
LEVT_FIRST_STARSOUL_IN			=	40046	--		首次星魂注入
LEVT_FIRST_STARSOUL_OUT			=	40047	--		首次星魂析出
LEVT_FIRST_STARSOUL_COMBINE		=	40048	--		首次星魂融合
LEVT_FIRST_RIDE					=	40049	--		首次骑乘
LEVT_FIRST_SNS					=	40050	--		首次社区激活角色
LEVT_FIRST_GTALK_TEAM			=	40051	--		首次组队语音
LEVT_FIRST_FRIEND_ADD			=	40052	--		首次添加好友
LEVT_FIRST_IN_TEAM				=	40053	--		首次加入队伍
LEVT_FIRST_MANUAL_LEVEL_UP		=	40054	--		首次手动升级
LEVT_FIRST_GTALK_LEAGUE			=	40055	--		首次军团语音
LEVT_FIRST_EQUIP_ENHANCE_TRANSFER=	40056	--		首次装备强化转移
LEVT_FIRST_LIGHT_LOGIN			=	40057	--		首次便携版登录
LEVT_FIRST_DOUBLE_EXP			=	40058	--		首次领取双倍经验
LEVT_FIRST_LEARN_TALENT			=	40059	--		首次学习天赋技能
LEVT_FIRST_HANGON				=	40060	--		首次慢节奏挂机成功
LEVT_FIRST_AUCTION_SELL			=	40061	--		首次拍卖卖出
LEVT_FIRST_AUCTION_BUY			=	40062	--		首次拍卖买入
LEVT_FIRST_DEAL_MONEY			=	40063	--		首次元宝交易
LEVT_FIRST_CHANGE_PROF			=	40064	--		首次改变职业
LEVT_FIRST_BOOTH				=	40065	--		首次摆摊
LEVT_FIRST_BOOTH_BUY_THERE		=	40066	--		首次在其他摊位买入
LEVT_FIRST_BOOTH_SELL			=	40067	--		首次摆摊卖出
LEVT_FIRST_BOOTH_BUY_HERE		=	40068	--		首次摆摊买入
LEVT_FIRST_AUTOLOCK_TIME		=	40069	--		首次设置时间锁
LEVT_FIRST_AUTOLOCK_PASSWORD	=	40070	--		首次设置密码锁
LEVT_FIRST_CHOOSE_PROF			=	40071	--		首次选择职业
LEVT_FIRST_SKILL_LEARN			=	40072	--		首次学习技能
LEVT_FIRST_CHAKRA				=	40073	--		首次爆发小宇宙
LEVT_FIRST_SKILL_EDIT			=	40074	--		首次编辑连招技能

LEVT_ASTROLOGY					=	40075	--		占星
LEVT_EQUIP_PROCESS				=	40076	--		装备加工
LEVT_EQUIP_ENHANCE				=	40077	--		装备强化
LEVT_MAGIC_BOX_COMBINE			=	40078	--		魔盒合成
LEVT_MAGIC_BOX_BREAK			=	40079	--		魔盒拆分
LEVT_CLOTH_STAR					=	40080	--		圣衣星铸
LEVT_PRAY						=	40081	--		沐浴荣光
LEVT_FIRST_USE_BIND_MONEY		=	40082	--		首次使用绑定币（星券）
LEVT_FIRST_USE_TITLE			=	40083	--		首次使用称号
LEVT_FIRST_OPEN_STORE			=	40084	--		首次打开仓库
LEVT_ACHIEVE_CONDITION_END		=	40140	


-- 其他事件
LEVT_FIRST_DIE_REVIVE			=	50001	--		首次死亡复活
LEVT_FIRST_MANUALLY_LEVEL_UP	=	50002	--		首次手动升级
LEVT_FIRST_GET_CLOTH			=	50003	--		首次获得圣衣
LEVT_FIRST_GET_TITLE			=	50004	--		首次获得称号
LEVT_FIRST_GET_PHOTOBOOK		=	50005	--		首次获得图鉴
LEVT_FIRST_GET_ACHIEVEMENT		=	50006	--		首次获得成就
LEVT_FIRST_SHORTCUT_FULL		=	50007	--		首次快捷栏满格

-- to delete	 	 
LEVT_FIRST_TRADE				=	50008	 			
LEVT_FIRST_SEL_MONSTER			=	50010	 
LEVT_FIRST_SEL_EGG_MONSTER		=	50011	 
LEVT_FIRST_SEL_CATCH_MONSTER	=	50012	 
LEVT_FIRST_SEL_BOSS_MONSTER		=	50013	 
LEVT_FIRST_SEL_PLAYER			=	50014	 
LEVT_FIRST_GAIN_BUFF			=	50015	 
LEVT_FIRST_BE_HEALED			=	50016	 	
LEVT_FIRST_RECEIVE_WHISPER		=	50017	  
LEVT_FIRST_TEAM_SETTING			=	50019	 
LEVT_FIRST_PLAYER_BIND			=	50020	 	 
LEVT_FIRST_JOIN_CORPS			=	50022	 
LEVT_FIRST_TRAINING_SUCCESS		=	50023
LEVT_FIRST_OPEN_SHOPING			=	50028	 
LEVT_FIRST_TASK_MAJOR			=	50029
LEVT_FIRST_TASK_LATERAL			=	50030
LEVT_FIRST_TASK_RISK			=	50031
LEVT_FIRST_TASK_SOCIAL			=	50032
LEVT_FIRST_TASK_FAILED			=	50033	
LEVT_FIRST_TASK_FULL			=	50034	 
LEVT_FIRST_TASK_REWORD			=	50035
LEVT_FIRST_TASK_TITLE			=	50036
LEVT_FIRST_TASK_PACK_FULL_FAIL  =	50037	 
LEVT_FIRST_VIEW_SKILL			=	50038
LEVT_FIRST_LOOT_ITEM			=	50039
LEVT_FIRST_PACK_FULL			=	50040	 	








